'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SqlQueries
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LotteryManagementSystem.SqlQueries", GetType(SqlQueries).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''
        '''
        '''--DECLARE @ApplicationName 			VARCHAR(128)
        '''--DECLARE @ApplicationVersion			VARCHAR(32)
        '''--DECLARE @ApplicationType			VARCHAR(32)
        '''--DECLARE @ApplicationPath			VARCHAR(255)
        '''--DECLARE @ApplicationAssemblyPath	VARCHAR(255)
        '''--DECLARE @ProcessUserIdentity		VARCHAR(255)
        '''--DECLARE @DeviceName					VARCHAR(255)
        '''--DECLARE @DeviceOs					VARCHAR(255)
        '''--DECLARE @IsOperatingSystem64Bit		bit
        '''--DECLARE @ProcessorCount				smallint
        '''--DECLARE @TotalPhyiscalMemory		bigint
        '''--DECLARE @TotalVirtualMemory			bigint [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property AddApplicationEnvironment() As String
            Get
                Return ResourceManager.GetString("AddApplicationEnvironment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --DECLARE @UserName     VARCHAR(16)
        '''--DECLARE @FirstName   VARCHAR(64)
        '''--DECLARE @LastName	VARCHAR(64)
        '''--DECLARE @Password   VARCHAR(64)
        '''
        '''
        '''--SET @UserName = &apos;edrisk&apos;
        '''--SET @FirstName = &apos;Edris&apos;
        '''--SET @LastName = &apos;Khestoo&apos;
        '''--SET @Password = &apos;123456&apos;
        '''
        '''DECLARE @PasswordDate DATETIME
        '''DECLARE @ReturnValue INT
        '''
        '''SET @PasswordDate = dbo.ufnGetAcctDateFromDate(GETDATE())
        '''SET @ReturnValue = 0
        '''
        '''-- Check if the UserID exists...
        '''IF EXISTS(SELECT * FROM dbo.AppUser WHERE UserName = @UserName)
        '''   BEGIN
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property AddUser() As String
            Get
                Return ResourceManager.GetString("AddUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''--DECLARE @AppUserID     Int
        '''--DECLARE @Password      VARCHAR(64)
        '''--DECLARE @PasswordReset BIT
        '''  
        '''--SET @AppUserID = 21
        '''--SET @Password = &apos;a776b2bf370eadebae6ee8191fa8a55d&apos;
        '''--SET @PasswordReset = 1
        '''
        '''-- Variable Declaration section
        '''DECLARE @Current INT
        '''DECLARE @History INT
        '''DECLARE @LastPasswordCount INT
        '''DECLARE @ReturnValue INT
        '''DECLARE @UpdateDate DATETIME
        '''DECLARE @PasswordTable TABLE ([Password] VARCHAR(128))
        '''DECLARE @PasswordHistoryON BIT
        '''
        '''-- Get and Set the AccountingDate
        '''SET @UpdateDa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property AppUpdatePassword() As String
            Get
                Return ResourceManager.GetString("AppUpdatePassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        '''--------------------------------------------------------------------------------
        '''Name: AuthenticateUser
        '''
        '''Desc: Authenticates user for the Lottery Management System.
        '''
        '''Return values: 
        '''   AppUser ID on success or
        '''   -1 = Invalid LoginID value.
        '''   -2 = DeActivated User.
        '''   -3 = Invalid password.
        '''   -4 = Account is locked.
        '''      
        '''Called by: Lottery Management System 
        '''
        '''Parameters:
        '''   @UserID     VarChar(16)     User login string
        '''   @Password   VarChar(64)     User password string
        '''
        '''Created on [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property AuthenticateUser() As String
            Get
                Return ResourceManager.GetString("AuthenticateUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''DECLARE @PartitionKey INT 
        '''SET @PartitionKey = DATEDIFF(D, &apos;1970-01-01 00:00:00&apos;, GETUTCDATE())
        '''
        '''DECLARE @UserId INT
        '''SET @UserId = NULL
        '''
        '''IF (@UserName IS NOT NULL)
        '''BEGIN
        '''	SELECT @UserId from AppUser where UserName = @UserName
        '''END
        '''
        '''INSERT EventLog (PartionKey, EventDate, EventTypeId, [Description], Details, EventSource, UserId)
        '''		   VALUES   (@PartitionKey, GETDATE(), @EventTypeId , @EventDescription, @Details, @EventSource , @UserId)
        '''.
        '''</summary>
        Friend Shared ReadOnly Property InsertEventLog() As String
            Get
                Return ResourceManager.GetString("InsertEventLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --DECLARE @AppUserID  Int,
        '''--   @UserName     VarChar(16),
        '''--   @FirstName   VarChar(64),
        '''--   @LastName   VarChar(64),
        '''--   @IsActive   Bit
        '''   
        '''
        '''-- Update data into AppUser table...
        '''UPDATE [AppUser] SET
        '''   UserName     = @UserName,
        '''   FirstName   = @FirstName,
        '''   LastName   = @LastName,
        '''   IsActive   = @IsActive
        '''WHERE AppUserID = @AppUserID
        '''
        '''-- Return the error value.
        '''SELECT @@ERROR
        '''.
        '''</summary>
        Friend Shared ReadOnly Property UpdateUser() As String
            Get
                Return ResourceManager.GetString("UpdateUser", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
