'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DSDealImport"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DSDealImport
    Inherits Global.System.Data.DataSet
    
    Private tableDTDealImport As DTDealImportDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("DTDealImport")) Is Nothing) Then
                MyBase.Tables.Add(New DTDealImportDataTable(ds.Tables("DTDealImport")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property DTDealImport() As DTDealImportDataTable
        Get
            Return Me.tableDTDealImport
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DSDealImport = CType(MyBase.Clone,DSDealImport)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("DTDealImport")) Is Nothing) Then
                MyBase.Tables.Add(New DTDealImportDataTable(ds.Tables("DTDealImport")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableDTDealImport = CType(MyBase.Tables("DTDealImport"),DTDealImportDataTable)
        If (initTable = true) Then
            If (Not (Me.tableDTDealImport) Is Nothing) Then
                Me.tableDTDealImport.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DSDealImport"
        Me.Prefix = ""
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableDTDealImport = New DTDealImportDataTable
        MyBase.Tables.Add(Me.tableDTDealImport)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeDTDealImport() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DSDealImport = New DSDealImport
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub DTDealImportRowChangeEventHandler(ByVal sender As Object, ByVal e As DTDealImportRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class DTDealImportDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnIMPORT_HISTORY_ID As Global.System.Data.DataColumn
        
        Private columnEXPORT_HISTORY_ID As Global.System.Data.DataColumn
        
        Private columnIMPORTED_BY As Global.System.Data.DataColumn
        
        Private columnEXPORTED_BY As Global.System.Data.DataColumn
        
        Private columnIMPORT_DATE As Global.System.Data.DataColumn
        
        Private columnEXPORT_DATE As Global.System.Data.DataColumn
        
        Private columnCASINO_UPDATE As Global.System.Data.DataColumn
        
        Private columnGAME_UPDATE As Global.System.Data.DataColumn
        
        Private columnBANK_UPDATE As Global.System.Data.DataColumn
        
        Private columnFORM_UPDATE As Global.System.Data.DataColumn
        
        Private columnIS_GENERIC As Global.System.Data.DataColumn
        
        Private columnSUCCESSFUL As Global.System.Data.DataColumn
        
        Private columnIMPORT_DETAIL_ID As Global.System.Data.DataColumn
        
        Private columnTABLE_NAME As Global.System.Data.DataColumn
        
        Private columnDETAIL_TEXT As Global.System.Data.DataColumn
        
        Private columnINSERT_COUNT As Global.System.Data.DataColumn
        
        Private columnUPDATE_COUNT As Global.System.Data.DataColumn
        
        Private columnIGNORED_COUNT As Global.System.Data.DataColumn
        
        Private columnERROR_COUNT As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "DTDealImport"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IMPORT_HISTORY_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIMPORT_HISTORY_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property EXPORT_HISTORY_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEXPORT_HISTORY_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IMPORTED_BYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIMPORTED_BY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property EXPORTED_BYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEXPORTED_BY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IMPORT_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIMPORT_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property EXPORT_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEXPORT_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CASINO_UPDATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCASINO_UPDATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property GAME_UPDATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGAME_UPDATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BANK_UPDATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBANK_UPDATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property FORM_UPDATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFORM_UPDATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IS_GENERICColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIS_GENERIC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SUCCESSFULColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSUCCESSFUL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IMPORT_DETAIL_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIMPORT_DETAIL_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TABLE_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTABLE_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DETAIL_TEXTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDETAIL_TEXT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property INSERT_COUNTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnINSERT_COUNT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property UPDATE_COUNTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUPDATE_COUNT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IGNORED_COUNTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIGNORED_COUNT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ERROR_COUNTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnERROR_COUNT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As DTDealImportRow
            Get
                Return CType(Me.Rows(index),DTDealImportRow)
            End Get
        End Property
        
        Public Event DTDealImportRowChanging As DTDealImportRowChangeEventHandler
        
        Public Event DTDealImportRowChanged As DTDealImportRowChangeEventHandler
        
        Public Event DTDealImportRowDeleting As DTDealImportRowChangeEventHandler
        
        Public Event DTDealImportRowDeleted As DTDealImportRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddDTDealImportRow(ByVal row As DTDealImportRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddDTDealImportRow( _
                    ByVal IMPORT_HISTORY_ID As Integer,  _
                    ByVal EXPORT_HISTORY_ID As Integer,  _
                    ByVal IMPORTED_BY As String,  _
                    ByVal EXPORTED_BY As String,  _
                    ByVal IMPORT_DATE As Date,  _
                    ByVal EXPORT_DATE As Date,  _
                    ByVal CASINO_UPDATE As Boolean,  _
                    ByVal GAME_UPDATE As Boolean,  _
                    ByVal BANK_UPDATE As Boolean,  _
                    ByVal FORM_UPDATE As Boolean,  _
                    ByVal IS_GENERIC As Boolean,  _
                    ByVal SUCCESSFUL As Boolean,  _
                    ByVal IMPORT_DETAIL_ID As Integer,  _
                    ByVal TABLE_NAME As String,  _
                    ByVal DETAIL_TEXT As String,  _
                    ByVal INSERT_COUNT As Integer,  _
                    ByVal UPDATE_COUNT As Integer,  _
                    ByVal IGNORED_COUNT As Integer,  _
                    ByVal ERROR_COUNT As Integer) As DTDealImportRow
            Dim rowDTDealImportRow As DTDealImportRow = CType(Me.NewRow,DTDealImportRow)
            Dim columnValuesArray() As Object = New Object() {IMPORT_HISTORY_ID, EXPORT_HISTORY_ID, IMPORTED_BY, EXPORTED_BY, IMPORT_DATE, EXPORT_DATE, CASINO_UPDATE, GAME_UPDATE, BANK_UPDATE, FORM_UPDATE, IS_GENERIC, SUCCESSFUL, IMPORT_DETAIL_ID, TABLE_NAME, DETAIL_TEXT, INSERT_COUNT, UPDATE_COUNT, IGNORED_COUNT, ERROR_COUNT}
            rowDTDealImportRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowDTDealImportRow)
            Return rowDTDealImportRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As DTDealImportDataTable = CType(MyBase.Clone,DTDealImportDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New DTDealImportDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnIMPORT_HISTORY_ID = MyBase.Columns("IMPORT_HISTORY_ID")
            Me.columnEXPORT_HISTORY_ID = MyBase.Columns("EXPORT_HISTORY_ID")
            Me.columnIMPORTED_BY = MyBase.Columns("IMPORTED_BY")
            Me.columnEXPORTED_BY = MyBase.Columns("EXPORTED_BY")
            Me.columnIMPORT_DATE = MyBase.Columns("IMPORT_DATE")
            Me.columnEXPORT_DATE = MyBase.Columns("EXPORT_DATE")
            Me.columnCASINO_UPDATE = MyBase.Columns("CASINO_UPDATE")
            Me.columnGAME_UPDATE = MyBase.Columns("GAME_UPDATE")
            Me.columnBANK_UPDATE = MyBase.Columns("BANK_UPDATE")
            Me.columnFORM_UPDATE = MyBase.Columns("FORM_UPDATE")
            Me.columnIS_GENERIC = MyBase.Columns("IS_GENERIC")
            Me.columnSUCCESSFUL = MyBase.Columns("SUCCESSFUL")
            Me.columnIMPORT_DETAIL_ID = MyBase.Columns("IMPORT_DETAIL_ID")
            Me.columnTABLE_NAME = MyBase.Columns("TABLE_NAME")
            Me.columnDETAIL_TEXT = MyBase.Columns("DETAIL_TEXT")
            Me.columnINSERT_COUNT = MyBase.Columns("INSERT_COUNT")
            Me.columnUPDATE_COUNT = MyBase.Columns("UPDATE_COUNT")
            Me.columnIGNORED_COUNT = MyBase.Columns("IGNORED_COUNT")
            Me.columnERROR_COUNT = MyBase.Columns("ERROR_COUNT")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnIMPORT_HISTORY_ID = New Global.System.Data.DataColumn("IMPORT_HISTORY_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIMPORT_HISTORY_ID)
            Me.columnEXPORT_HISTORY_ID = New Global.System.Data.DataColumn("EXPORT_HISTORY_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEXPORT_HISTORY_ID)
            Me.columnIMPORTED_BY = New Global.System.Data.DataColumn("IMPORTED_BY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIMPORTED_BY)
            Me.columnEXPORTED_BY = New Global.System.Data.DataColumn("EXPORTED_BY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEXPORTED_BY)
            Me.columnIMPORT_DATE = New Global.System.Data.DataColumn("IMPORT_DATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIMPORT_DATE)
            Me.columnEXPORT_DATE = New Global.System.Data.DataColumn("EXPORT_DATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEXPORT_DATE)
            Me.columnCASINO_UPDATE = New Global.System.Data.DataColumn("CASINO_UPDATE", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCASINO_UPDATE)
            Me.columnGAME_UPDATE = New Global.System.Data.DataColumn("GAME_UPDATE", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGAME_UPDATE)
            Me.columnBANK_UPDATE = New Global.System.Data.DataColumn("BANK_UPDATE", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBANK_UPDATE)
            Me.columnFORM_UPDATE = New Global.System.Data.DataColumn("FORM_UPDATE", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFORM_UPDATE)
            Me.columnIS_GENERIC = New Global.System.Data.DataColumn("IS_GENERIC", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIS_GENERIC)
            Me.columnSUCCESSFUL = New Global.System.Data.DataColumn("SUCCESSFUL", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSUCCESSFUL)
            Me.columnIMPORT_DETAIL_ID = New Global.System.Data.DataColumn("IMPORT_DETAIL_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIMPORT_DETAIL_ID)
            Me.columnTABLE_NAME = New Global.System.Data.DataColumn("TABLE_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTABLE_NAME)
            Me.columnDETAIL_TEXT = New Global.System.Data.DataColumn("DETAIL_TEXT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDETAIL_TEXT)
            Me.columnINSERT_COUNT = New Global.System.Data.DataColumn("INSERT_COUNT", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnINSERT_COUNT)
            Me.columnUPDATE_COUNT = New Global.System.Data.DataColumn("UPDATE_COUNT", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUPDATE_COUNT)
            Me.columnIGNORED_COUNT = New Global.System.Data.DataColumn("IGNORED_COUNT", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIGNORED_COUNT)
            Me.columnERROR_COUNT = New Global.System.Data.DataColumn("ERROR_COUNT", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnERROR_COUNT)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewDTDealImportRow() As DTDealImportRow
            Return CType(Me.NewRow,DTDealImportRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New DTDealImportRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(DTDealImportRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.DTDealImportRowChangedEvent) Is Nothing) Then
                RaiseEvent DTDealImportRowChanged(Me, New DTDealImportRowChangeEvent(CType(e.Row,DTDealImportRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.DTDealImportRowChangingEvent) Is Nothing) Then
                RaiseEvent DTDealImportRowChanging(Me, New DTDealImportRowChangeEvent(CType(e.Row,DTDealImportRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.DTDealImportRowDeletedEvent) Is Nothing) Then
                RaiseEvent DTDealImportRowDeleted(Me, New DTDealImportRowChangeEvent(CType(e.Row,DTDealImportRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.DTDealImportRowDeletingEvent) Is Nothing) Then
                RaiseEvent DTDealImportRowDeleting(Me, New DTDealImportRowChangeEvent(CType(e.Row,DTDealImportRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveDTDealImportRow(ByVal row As DTDealImportRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DSDealImport = New DSDealImport
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "DTDealImportDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class DTDealImportRow
        Inherits Global.System.Data.DataRow
        
        Private tableDTDealImport As DTDealImportDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableDTDealImport = CType(Me.Table,DTDealImportDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IMPORT_HISTORY_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.IMPORT_HISTORY_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IMPORT_HISTORY_ID' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.IMPORT_HISTORY_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property EXPORT_HISTORY_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.EXPORT_HISTORY_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EXPORT_HISTORY_ID' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.EXPORT_HISTORY_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IMPORTED_BY() As String
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.IMPORTED_BYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IMPORTED_BY' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.IMPORTED_BYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property EXPORTED_BY() As String
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.EXPORTED_BYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EXPORTED_BY' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.EXPORTED_BYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IMPORT_DATE() As Date
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.IMPORT_DATEColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IMPORT_DATE' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.IMPORT_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property EXPORT_DATE() As Date
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.EXPORT_DATEColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EXPORT_DATE' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.EXPORT_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CASINO_UPDATE() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.CASINO_UPDATEColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CASINO_UPDATE' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.CASINO_UPDATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GAME_UPDATE() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.GAME_UPDATEColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'GAME_UPDATE' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.GAME_UPDATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BANK_UPDATE() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.BANK_UPDATEColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BANK_UPDATE' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.BANK_UPDATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property FORM_UPDATE() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.FORM_UPDATEColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FORM_UPDATE' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.FORM_UPDATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IS_GENERIC() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.IS_GENERICColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IS_GENERIC' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.IS_GENERICColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SUCCESSFUL() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.SUCCESSFULColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SUCCESSFUL' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.SUCCESSFULColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IMPORT_DETAIL_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.IMPORT_DETAIL_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IMPORT_DETAIL_ID' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.IMPORT_DETAIL_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TABLE_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.TABLE_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TABLE_NAME' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.TABLE_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DETAIL_TEXT() As String
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.DETAIL_TEXTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DETAIL_TEXT' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.DETAIL_TEXTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property INSERT_COUNT() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.INSERT_COUNTColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'INSERT_COUNT' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.INSERT_COUNTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UPDATE_COUNT() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.UPDATE_COUNTColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'UPDATE_COUNT' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.UPDATE_COUNTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IGNORED_COUNT() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.IGNORED_COUNTColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IGNORED_COUNT' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.IGNORED_COUNTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ERROR_COUNT() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTDealImport.ERROR_COUNTColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ERROR_COUNT' in table 'DTDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTDealImport.ERROR_COUNTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIMPORT_HISTORY_IDNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.IMPORT_HISTORY_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIMPORT_HISTORY_IDNull()
            Me(Me.tableDTDealImport.IMPORT_HISTORY_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsEXPORT_HISTORY_IDNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.EXPORT_HISTORY_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetEXPORT_HISTORY_IDNull()
            Me(Me.tableDTDealImport.EXPORT_HISTORY_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIMPORTED_BYNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.IMPORTED_BYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIMPORTED_BYNull()
            Me(Me.tableDTDealImport.IMPORTED_BYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsEXPORTED_BYNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.EXPORTED_BYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetEXPORTED_BYNull()
            Me(Me.tableDTDealImport.EXPORTED_BYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIMPORT_DATENull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.IMPORT_DATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIMPORT_DATENull()
            Me(Me.tableDTDealImport.IMPORT_DATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsEXPORT_DATENull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.EXPORT_DATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetEXPORT_DATENull()
            Me(Me.tableDTDealImport.EXPORT_DATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCASINO_UPDATENull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.CASINO_UPDATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCASINO_UPDATENull()
            Me(Me.tableDTDealImport.CASINO_UPDATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGAME_UPDATENull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.GAME_UPDATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGAME_UPDATENull()
            Me(Me.tableDTDealImport.GAME_UPDATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBANK_UPDATENull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.BANK_UPDATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBANK_UPDATENull()
            Me(Me.tableDTDealImport.BANK_UPDATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsFORM_UPDATENull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.FORM_UPDATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetFORM_UPDATENull()
            Me(Me.tableDTDealImport.FORM_UPDATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIS_GENERICNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.IS_GENERICColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIS_GENERICNull()
            Me(Me.tableDTDealImport.IS_GENERICColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSUCCESSFULNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.SUCCESSFULColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSUCCESSFULNull()
            Me(Me.tableDTDealImport.SUCCESSFULColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIMPORT_DETAIL_IDNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.IMPORT_DETAIL_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIMPORT_DETAIL_IDNull()
            Me(Me.tableDTDealImport.IMPORT_DETAIL_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTABLE_NAMENull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.TABLE_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTABLE_NAMENull()
            Me(Me.tableDTDealImport.TABLE_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDETAIL_TEXTNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.DETAIL_TEXTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDETAIL_TEXTNull()
            Me(Me.tableDTDealImport.DETAIL_TEXTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsINSERT_COUNTNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.INSERT_COUNTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetINSERT_COUNTNull()
            Me(Me.tableDTDealImport.INSERT_COUNTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsUPDATE_COUNTNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.UPDATE_COUNTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetUPDATE_COUNTNull()
            Me(Me.tableDTDealImport.UPDATE_COUNTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIGNORED_COUNTNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.IGNORED_COUNTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIGNORED_COUNTNull()
            Me(Me.tableDTDealImport.IGNORED_COUNTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsERROR_COUNTNull() As Boolean
            Return Me.IsNull(Me.tableDTDealImport.ERROR_COUNTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetERROR_COUNTNull()
            Me(Me.tableDTDealImport.ERROR_COUNTColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class DTDealImportRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As DTDealImportRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As DTDealImportRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As DTDealImportRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
