'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DSMasterDealImport"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DSMasterDealImport
    Inherits Global.System.Data.DataSet
    
    Private tableDTMasterDealImport As DTMasterDealImportDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("DTMasterDealImport")) Is Nothing) Then
                MyBase.Tables.Add(New DTMasterDealImportDataTable(ds.Tables("DTMasterDealImport")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property DTMasterDealImport() As DTMasterDealImportDataTable
        Get
            Return Me.tableDTMasterDealImport
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DSMasterDealImport = CType(MyBase.Clone,DSMasterDealImport)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("DTMasterDealImport")) Is Nothing) Then
                MyBase.Tables.Add(New DTMasterDealImportDataTable(ds.Tables("DTMasterDealImport")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableDTMasterDealImport = CType(MyBase.Tables("DTMasterDealImport"),DTMasterDealImportDataTable)
        If (initTable = true) Then
            If (Not (Me.tableDTMasterDealImport) Is Nothing) Then
                Me.tableDTMasterDealImport.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DSMasterDealImport"
        Me.Prefix = ""
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableDTMasterDealImport = New DTMasterDealImportDataTable
        MyBase.Tables.Add(Me.tableDTMasterDealImport)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeDTMasterDealImport() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DSMasterDealImport = New DSMasterDealImport
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub DTMasterDealImportRowChangeEventHandler(ByVal sender As Object, ByVal e As DTMasterDealImportRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class DTMasterDealImportDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnIMPORT_MD_HISTORY_ID As Global.System.Data.DataColumn
        
        Private columnIMPORTED_BY As Global.System.Data.DataColumn
        
        Private columnIMPORT_DATE As Global.System.Data.DataColumn
        
        Private columnCASINO_UPDATE As Global.System.Data.DataColumn
        
        Private columnBANK_MACHINE_UPDATE As Global.System.Data.DataColumn
        
        Private columnSUCCESSFUL As Global.System.Data.DataColumn
        
        Private columnIMPORT_MD_DETAIL_ID As Global.System.Data.DataColumn
        
        Private columnTABLE_NAME As Global.System.Data.DataColumn
        
        Private columnDETAIL_TEXT As Global.System.Data.DataColumn
        
        Private columnINSERT_COUNT As Global.System.Data.DataColumn
        
        Private columnUPDATE_COUNT As Global.System.Data.DataColumn
        
        Private columnIGNORED_COUNT As Global.System.Data.DataColumn
        
        Private columnERROR_COUNT As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "DTMasterDealImport"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IMPORT_MD_HISTORY_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIMPORT_MD_HISTORY_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IMPORTED_BYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIMPORTED_BY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IMPORT_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIMPORT_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CASINO_UPDATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCASINO_UPDATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BANK_MACHINE_UPDATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBANK_MACHINE_UPDATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SUCCESSFULColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSUCCESSFUL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IMPORT_MD_DETAIL_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIMPORT_MD_DETAIL_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TABLE_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTABLE_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DETAIL_TEXTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDETAIL_TEXT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property INSERT_COUNTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnINSERT_COUNT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property UPDATE_COUNTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUPDATE_COUNT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IGNORED_COUNTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIGNORED_COUNT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ERROR_COUNTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnERROR_COUNT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As DTMasterDealImportRow
            Get
                Return CType(Me.Rows(index),DTMasterDealImportRow)
            End Get
        End Property
        
        Public Event DTMasterDealImportRowChanging As DTMasterDealImportRowChangeEventHandler
        
        Public Event DTMasterDealImportRowChanged As DTMasterDealImportRowChangeEventHandler
        
        Public Event DTMasterDealImportRowDeleting As DTMasterDealImportRowChangeEventHandler
        
        Public Event DTMasterDealImportRowDeleted As DTMasterDealImportRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddDTMasterDealImportRow(ByVal row As DTMasterDealImportRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddDTMasterDealImportRow(ByVal IMPORT_MD_HISTORY_ID As Integer, ByVal IMPORTED_BY As String, ByVal IMPORT_DATE As Date, ByVal CASINO_UPDATE As Boolean, ByVal BANK_MACHINE_UPDATE As Boolean, ByVal SUCCESSFUL As Boolean, ByVal IMPORT_MD_DETAIL_ID As Integer, ByVal TABLE_NAME As String, ByVal DETAIL_TEXT As String, ByVal INSERT_COUNT As Integer, ByVal UPDATE_COUNT As Integer, ByVal IGNORED_COUNT As Integer, ByVal ERROR_COUNT As Integer) As DTMasterDealImportRow
            Dim rowDTMasterDealImportRow As DTMasterDealImportRow = CType(Me.NewRow,DTMasterDealImportRow)
            Dim columnValuesArray() As Object = New Object() {IMPORT_MD_HISTORY_ID, IMPORTED_BY, IMPORT_DATE, CASINO_UPDATE, BANK_MACHINE_UPDATE, SUCCESSFUL, IMPORT_MD_DETAIL_ID, TABLE_NAME, DETAIL_TEXT, INSERT_COUNT, UPDATE_COUNT, IGNORED_COUNT, ERROR_COUNT}
            rowDTMasterDealImportRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowDTMasterDealImportRow)
            Return rowDTMasterDealImportRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As DTMasterDealImportDataTable = CType(MyBase.Clone,DTMasterDealImportDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New DTMasterDealImportDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnIMPORT_MD_HISTORY_ID = MyBase.Columns("IMPORT_MD_HISTORY_ID")
            Me.columnIMPORTED_BY = MyBase.Columns("IMPORTED_BY")
            Me.columnIMPORT_DATE = MyBase.Columns("IMPORT_DATE")
            Me.columnCASINO_UPDATE = MyBase.Columns("CASINO_UPDATE")
            Me.columnBANK_MACHINE_UPDATE = MyBase.Columns("BANK_MACHINE_UPDATE")
            Me.columnSUCCESSFUL = MyBase.Columns("SUCCESSFUL")
            Me.columnIMPORT_MD_DETAIL_ID = MyBase.Columns("IMPORT_MD_DETAIL_ID")
            Me.columnTABLE_NAME = MyBase.Columns("TABLE_NAME")
            Me.columnDETAIL_TEXT = MyBase.Columns("DETAIL_TEXT")
            Me.columnINSERT_COUNT = MyBase.Columns("INSERT_COUNT")
            Me.columnUPDATE_COUNT = MyBase.Columns("UPDATE_COUNT")
            Me.columnIGNORED_COUNT = MyBase.Columns("IGNORED_COUNT")
            Me.columnERROR_COUNT = MyBase.Columns("ERROR_COUNT")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnIMPORT_MD_HISTORY_ID = New Global.System.Data.DataColumn("IMPORT_MD_HISTORY_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIMPORT_MD_HISTORY_ID)
            Me.columnIMPORTED_BY = New Global.System.Data.DataColumn("IMPORTED_BY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIMPORTED_BY)
            Me.columnIMPORT_DATE = New Global.System.Data.DataColumn("IMPORT_DATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIMPORT_DATE)
            Me.columnCASINO_UPDATE = New Global.System.Data.DataColumn("CASINO_UPDATE", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCASINO_UPDATE)
            Me.columnBANK_MACHINE_UPDATE = New Global.System.Data.DataColumn("BANK_MACHINE_UPDATE", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBANK_MACHINE_UPDATE)
            Me.columnSUCCESSFUL = New Global.System.Data.DataColumn("SUCCESSFUL", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSUCCESSFUL)
            Me.columnIMPORT_MD_DETAIL_ID = New Global.System.Data.DataColumn("IMPORT_MD_DETAIL_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIMPORT_MD_DETAIL_ID)
            Me.columnTABLE_NAME = New Global.System.Data.DataColumn("TABLE_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTABLE_NAME)
            Me.columnDETAIL_TEXT = New Global.System.Data.DataColumn("DETAIL_TEXT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDETAIL_TEXT)
            Me.columnINSERT_COUNT = New Global.System.Data.DataColumn("INSERT_COUNT", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnINSERT_COUNT)
            Me.columnUPDATE_COUNT = New Global.System.Data.DataColumn("UPDATE_COUNT", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUPDATE_COUNT)
            Me.columnIGNORED_COUNT = New Global.System.Data.DataColumn("IGNORED_COUNT", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIGNORED_COUNT)
            Me.columnERROR_COUNT = New Global.System.Data.DataColumn("ERROR_COUNT", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnERROR_COUNT)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewDTMasterDealImportRow() As DTMasterDealImportRow
            Return CType(Me.NewRow,DTMasterDealImportRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New DTMasterDealImportRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(DTMasterDealImportRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.DTMasterDealImportRowChangedEvent) Is Nothing) Then
                RaiseEvent DTMasterDealImportRowChanged(Me, New DTMasterDealImportRowChangeEvent(CType(e.Row,DTMasterDealImportRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.DTMasterDealImportRowChangingEvent) Is Nothing) Then
                RaiseEvent DTMasterDealImportRowChanging(Me, New DTMasterDealImportRowChangeEvent(CType(e.Row,DTMasterDealImportRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.DTMasterDealImportRowDeletedEvent) Is Nothing) Then
                RaiseEvent DTMasterDealImportRowDeleted(Me, New DTMasterDealImportRowChangeEvent(CType(e.Row,DTMasterDealImportRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.DTMasterDealImportRowDeletingEvent) Is Nothing) Then
                RaiseEvent DTMasterDealImportRowDeleting(Me, New DTMasterDealImportRowChangeEvent(CType(e.Row,DTMasterDealImportRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveDTMasterDealImportRow(ByVal row As DTMasterDealImportRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DSMasterDealImport = New DSMasterDealImport
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "DTMasterDealImportDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class DTMasterDealImportRow
        Inherits Global.System.Data.DataRow
        
        Private tableDTMasterDealImport As DTMasterDealImportDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableDTMasterDealImport = CType(Me.Table,DTMasterDealImportDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IMPORT_MD_HISTORY_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.IMPORT_MD_HISTORY_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IMPORT_MD_HISTORY_ID' in table 'DTMasterDealImport' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.IMPORT_MD_HISTORY_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IMPORTED_BY() As String
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.IMPORTED_BYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IMPORTED_BY' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.IMPORTED_BYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IMPORT_DATE() As Date
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.IMPORT_DATEColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IMPORT_DATE' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.IMPORT_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CASINO_UPDATE() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.CASINO_UPDATEColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CASINO_UPDATE' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.CASINO_UPDATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BANK_MACHINE_UPDATE() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.BANK_MACHINE_UPDATEColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BANK_MACHINE_UPDATE' in table 'DTMasterDealImport' is DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.BANK_MACHINE_UPDATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SUCCESSFUL() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.SUCCESSFULColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SUCCESSFUL' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.SUCCESSFULColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IMPORT_MD_DETAIL_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.IMPORT_MD_DETAIL_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IMPORT_MD_DETAIL_ID' in table 'DTMasterDealImport' is DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.IMPORT_MD_DETAIL_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TABLE_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.TABLE_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TABLE_NAME' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.TABLE_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DETAIL_TEXT() As String
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.DETAIL_TEXTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DETAIL_TEXT' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.DETAIL_TEXTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property INSERT_COUNT() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.INSERT_COUNTColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'INSERT_COUNT' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.INSERT_COUNTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UPDATE_COUNT() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.UPDATE_COUNTColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'UPDATE_COUNT' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.UPDATE_COUNTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IGNORED_COUNT() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.IGNORED_COUNTColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IGNORED_COUNT' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.IGNORED_COUNTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ERROR_COUNT() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDTMasterDealImport.ERROR_COUNTColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ERROR_COUNT' in table 'DTMasterDealImport' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDTMasterDealImport.ERROR_COUNTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIMPORT_MD_HISTORY_IDNull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.IMPORT_MD_HISTORY_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIMPORT_MD_HISTORY_IDNull()
            Me(Me.tableDTMasterDealImport.IMPORT_MD_HISTORY_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIMPORTED_BYNull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.IMPORTED_BYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIMPORTED_BYNull()
            Me(Me.tableDTMasterDealImport.IMPORTED_BYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIMPORT_DATENull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.IMPORT_DATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIMPORT_DATENull()
            Me(Me.tableDTMasterDealImport.IMPORT_DATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCASINO_UPDATENull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.CASINO_UPDATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCASINO_UPDATENull()
            Me(Me.tableDTMasterDealImport.CASINO_UPDATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBANK_MACHINE_UPDATENull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.BANK_MACHINE_UPDATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBANK_MACHINE_UPDATENull()
            Me(Me.tableDTMasterDealImport.BANK_MACHINE_UPDATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSUCCESSFULNull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.SUCCESSFULColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSUCCESSFULNull()
            Me(Me.tableDTMasterDealImport.SUCCESSFULColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIMPORT_MD_DETAIL_IDNull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.IMPORT_MD_DETAIL_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIMPORT_MD_DETAIL_IDNull()
            Me(Me.tableDTMasterDealImport.IMPORT_MD_DETAIL_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTABLE_NAMENull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.TABLE_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTABLE_NAMENull()
            Me(Me.tableDTMasterDealImport.TABLE_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDETAIL_TEXTNull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.DETAIL_TEXTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDETAIL_TEXTNull()
            Me(Me.tableDTMasterDealImport.DETAIL_TEXTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsINSERT_COUNTNull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.INSERT_COUNTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetINSERT_COUNTNull()
            Me(Me.tableDTMasterDealImport.INSERT_COUNTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsUPDATE_COUNTNull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.UPDATE_COUNTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetUPDATE_COUNTNull()
            Me(Me.tableDTMasterDealImport.UPDATE_COUNTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIGNORED_COUNTNull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.IGNORED_COUNTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIGNORED_COUNTNull()
            Me(Me.tableDTMasterDealImport.IGNORED_COUNTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsERROR_COUNTNull() As Boolean
            Return Me.IsNull(Me.tableDTMasterDealImport.ERROR_COUNTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetERROR_COUNTNull()
            Me(Me.tableDTMasterDealImport.ERROR_COUNTColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class DTMasterDealImportRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As DTMasterDealImportRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As DTMasterDealImportRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As DTMasterDealImportRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
