CREATE TABLE [dbo].[DEAL_SETUP]
(
[DEAL_NO] [int] NOT NULL,
[TYPE_ID] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEAL_DESCR] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMB_ROLLS] [int] NULL,
[TABS_PER_ROLL] [int] NULL,
[TAB_AMT] [smallmoney] NULL,
[COST_PER_TAB] [smallmoney] NULL,
[CREATED_BY] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SETUP_DATE] [datetime] NULL,
[JP_AMOUNT] [money] NULL,
[FORM_NUMB] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GAME_CODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_OPEN] [bit] NOT NULL,
[CLOSE_DATE] [datetime] NULL,
[CLOSE_RECOMMENDED] [bit] NOT NULL,
[CLOSED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DENOMINATION] [smallmoney] NULL,
[COINS_BET] [smallint] NOT NULL,
[LINES_BET] [tinyint] NOT NULL,
[EXPORTED_DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEAL_SETUP] ADD CONSTRAINT [PK_DEAL_SETUP] PRIMARY KEY CLUSTERED  ([DEAL_NO]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
