CREATE TABLE [dbo].[DB_INFO]
(
[DB_INFO_ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[UPGRADE_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPGRADE_DATE] [datetime] NOT NULL,
[SQL_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQL_EDITION] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQL_SERVICE_PACK] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERVER_NAME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPU_COUNT] [smallint] NOT NULL,
[PHYSICAL_MEMORY] [int] NOT NULL,
[VIRTUAL_MEMORY] [int] NOT NULL,
[LocationID] [int] NOT NULL,
[DatabaseName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DB_INFO] ADD CONSTRAINT [PK_DB_INFO] PRIMARY KEY CLUSTERED  ([DB_INFO_ID], [LocationID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
