CREATE TABLE [dbo].[VOUCHER]
(
[VOUCHER_ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[LOCATION_ID] [int] NOT NULL,
[VOUCHER_TYPE] [smallint] NOT NULL,
[BARCODE] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VOUCHER_AMOUNT] [money] NOT NULL,
[CREATE_DATE] [datetime] NOT NULL,
[CREATED_LOC] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REDEEMED_LOC] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REDEEMED_STATE] [bit] NOT NULL,
[REDEEMED_DATE] [datetime] NULL,
[CHECK_VALUE] [varbinary] (8) NULL,
[CT_TRANS_NO_VC] [int] NOT NULL,
[CT_TRANS_NO_VR] [int] NOT NULL,
[CT_TRANS_NO_JP] [int] NOT NULL,
[IS_VALID] [bit] NOT NULL,
[SESSION_PLAY_AMOUNT] [money] NOT NULL,
[UCV_TRANSFERRED] [bit] NOT NULL,
[UCV_TRANSFER_DATE] [datetime] NULL,
[GAME_TITLE_ID] [int] NOT NULL,
[PROMO_VOUCHER_SESSION_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHER] ADD CONSTRAINT [PK_VOUCHER] PRIMARY KEY CLUSTERED  ([VOUCHER_ID], [LOCATION_ID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
