CREATE TABLE [dbo].[TAB_ERROR]
(
[TAB_ERROR_ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[MACH_NO] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ERROR_NO] [int] NOT NULL,
[EVENT_TIME] [datetime] NOT NULL,
[LOCATION_ID] [int] NOT NULL,
[TICKET_NO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAB_ERROR] ADD CONSTRAINT [PK_TAB_ERROR] PRIMARY KEY CLUSTERED  ([TAB_ERROR_ID], [LOCATION_ID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
