CREATE TABLE [dbo].[LINES_BET_TO_GAME_TYPE]
(
[LINES_BET] [tinyint] NOT NULL,
[GAME_TYPE_CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LINES_BET_TO_GAME_TYPE] ADD CONSTRAINT [PK_LINES_BET_TO_GAME_TYPE] PRIMARY KEY CLUSTERED  ([GAME_TYPE_CODE], [LINES_BET]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LINES_BET_TO_GAME_TYPE] ADD CONSTRAINT [FK_LINES_BET_TO_GAME_TYPE_GAME_TYPE] FOREIGN KEY ([GAME_TYPE_CODE]) REFERENCES [dbo].[GAME_TYPE] ([GAME_TYPE_CODE])
GO
EXEC sp_addextendedproperty N'MS_Description', N'Stores the valid Lines Bet values for Game Types', 'SCHEMA', N'dbo', 'TABLE', N'LINES_BET_TO_GAME_TYPE', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Game Type Code', 'SCHEMA', N'dbo', 'TABLE', N'LINES_BET_TO_GAME_TYPE', 'COLUMN', N'GAME_TYPE_CODE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Valid Number of Lines Bet for Game Type', 'SCHEMA', N'dbo', 'TABLE', N'LINES_BET_TO_GAME_TYPE', 'COLUMN', N'LINES_BET'
GO
