CREATE TABLE [dbo].[VOUCHER_LOT]
(
[VOUCHER_LOT_ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[LOCATION_ID] [int] NOT NULL,
[LOT_NUMBER] [char] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_RECEIVED] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHER_LOT] ADD CONSTRAINT [PK_VOUCHER_LOT_1] PRIMARY KEY CLUSTERED  ([VOUCHER_LOT_ID], [LOCATION_ID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
