CREATE TABLE [dbo].[MACH_SETUP]
(
[MACH_NO] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOCATION_ID] [int] NOT NULL,
[MODEL_DESC] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TYPE_ID] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GAME_CODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_NO] [int] NULL,
[CASINO_MACH_NO] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IP_ADDRESS] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLAY_STATUS] [bit] NOT NULL,
[PLAY_STATUS_CHANGED] [datetime] NULL,
[ACTIVE_FLAG] [tinyint] NOT NULL,
[REMOVED_FLAG] [bit] NOT NULL,
[BALANCE] [money] NOT NULL,
[PROMO_BALANCE] [money] NOT NULL,
[LAST_ACTIVITY] [datetime] NULL,
[LAST_CONNECT] [datetime] NULL,
[LAST_DISCONNECT] [datetime] NULL,
[MACH_SERIAL_NO] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VOUCHER_PRINTING] [bit] NOT NULL,
[METER_TRANS_NO] [int] NOT NULL,
[SD_RS_FLAG] [bit] NOT NULL,
[GAME_RELEASE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GAME_CORE_LIB_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GAME_LIB_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MATH_DLL_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MATH_LIB_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OS_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYSTEM_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYSTEM_LIB_A_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYSTEM_CORE_LIB_VERSION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InstallDate] [datetime] NULL,
[RemoveDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MACH_SETUP] ADD CONSTRAINT [PK_MACH_SETUP] PRIMARY KEY CLUSTERED  ([MACH_NO], [LOCATION_ID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
