CREATE TABLE [dbo].[JACKPOT]
(
[TRANS_NO] [int] NOT NULL,
[DTIMESTAMP] [datetime] NOT NULL,
[CARD_ACCT_NO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MACH_NO] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CASINO_MACH_NO] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEAL_NO] [int] NOT NULL,
[TICKET_NO] [int] NOT NULL,
[PLAY_COST] [smallmoney] NOT NULL,
[TRANS_ID] [smallint] NOT NULL,
[TRANS_AMT] [money] NOT NULL,
[PROG_AMT] [money] NOT NULL,
[LOCATION_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JACKPOT] ADD CONSTRAINT [PK_JACKPOT] PRIMARY KEY CLUSTERED  ([TRANS_NO], [LOCATION_ID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
