CREATE TABLE [dbo].[DEAL_STATS]
(
[DEAL_NO] [int] NOT NULL,
[PLAY_COUNT] [int] NOT NULL,
[WIN_COUNT] [int] NOT NULL,
[LOSS_COUNT] [int] NOT NULL,
[FORFEIT_COUNT] [int] NOT NULL,
[JACKPOT_COUNT] [int] NOT NULL,
[AMOUNT_PLAYED] [money] NOT NULL,
[TOTAL_WIN_AMOUNT] [money] NOT NULL,
[BASE_AMOUNT_WON] [money] NOT NULL,
[PROG_AMOUNT_WON] [money] NOT NULL,
[AMOUNT_FORFEITED] [money] NOT NULL,
[PROG_CONTRIBUTION] [money] NOT NULL,
[FIRST_PLAY] [datetime] NULL,
[LAST_PLAY] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEAL_STATS] ADD CONSTRAINT [PK_DEAL_STATS] PRIMARY KEY CLUSTERED  ([DEAL_NO]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
