CREATE TABLE [dbo].[PROGRESSIVE_POOL]
(
[PROGRESSIVE_POOL_ID] [int] NOT NULL,
[PROGRESSIVE_TYPE_ID] [int] NOT NULL,
[GAME_TYPE_CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DENOMINATION] [int] NOT NULL,
[COINS_BET] [smallint] NOT NULL,
[LINES_BET] [tinyint] NOT NULL,
[POOL_1] [money] NOT NULL,
[POOL_2] [money] NOT NULL,
[POOL_3] [money] NOT NULL,
[WinLevel] [tinyint] NOT NULL,
[SeedCount] [int] NOT NULL,
[Rate1] [decimal] (5, 4) NOT NULL,
[Rate2] [decimal] (5, 4) NOT NULL,
[Rate3] [decimal] (5, 4) NOT NULL,
[LocationID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROGRESSIVE_POOL] ADD CONSTRAINT [PK_PROGRESSIVE_POOL] PRIMARY KEY CLUSTERED  ([PROGRESSIVE_POOL_ID], [LocationID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
