CREATE TABLE [dbo].[SET_FUNCTIONS_PERM]
(
[LEVEL_CODE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FUNC_ID] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SET_FUNCTIONS_PERM] ADD CONSTRAINT [PK_SET_FUNCTIONS_PERM] PRIMARY KEY CLUSTERED  ([LEVEL_CODE], [FUNC_ID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SET_FUNCTIONS_PERM] WITH NOCHECK ADD CONSTRAINT [FK_SET_FUNCTIONS_PERM_LEVEL_PERMISSIONS] FOREIGN KEY ([LEVEL_CODE]) REFERENCES [dbo].[LEVEL_PERMISSIONS] ([LEVEL_CODE])
GO
ALTER TABLE [dbo].[SET_FUNCTIONS_PERM] WITH NOCHECK ADD CONSTRAINT [FK_SET_FUNCTIONS_PERM_SYS_FUNCTIONS] FOREIGN KEY ([FUNC_ID]) REFERENCES [dbo].[SYS_FUNCTIONS] ([FUNC_ID])
GO
EXEC sp_addextendedproperty N'MS_Description', N'Joins SYS_FUNCTIONS to LEVEL_PERMISSIONS group table. Controls access to Accounting app menu items.', 'SCHEMA', N'dbo', 'TABLE', N'SET_FUNCTIONS_PERM', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Function ID links to SYS_FUNCTIONS', 'SCHEMA', N'dbo', 'TABLE', N'SET_FUNCTIONS_PERM', 'COLUMN', N'FUNC_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'User level', 'SCHEMA', N'dbo', 'TABLE', N'SET_FUNCTIONS_PERM', 'COLUMN', N'LEVEL_CODE'
GO
