CREATE TABLE [dbo].[MACH_SETUP_GAMES]
(
[MACH_NO] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOCATION_ID] [int] NOT NULL,
[GAME_CODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BANK_NO] [int] NOT NULL,
[TYPE_ID] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GAME_RELEASE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MATH_DLL_VERSION] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MATH_LIB_VERSION] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsEnabled] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MACH_SETUP_GAMES] ADD CONSTRAINT [PK_MACH_NO_GAME_CODE] PRIMARY KEY CLUSTERED  ([MACH_NO], [GAME_CODE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MACH_SETUP_GAMES] ADD CONSTRAINT [FK_MACH_SETUP_MACH_NO] FOREIGN KEY ([MACH_NO], [LOCATION_ID]) REFERENCES [dbo].[MACH_SETUP] ([MACH_NO], [LOCATION_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
