CREATE TABLE [dbo].[PROG_AWARD_FACTOR]
(
[PROG_AWARD_FACTOR_ID] [int] NOT NULL,
[PROGRESSIVE_TYPE_ID] [int] NOT NULL,
[TIER_LEVEL] [smallint] NOT NULL,
[AWARD_FACTOR] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROG_AWARD_FACTOR] ADD CONSTRAINT [PK_PROG_AWARD_FACTOR] PRIMARY KEY CLUSTERED  ([PROG_AWARD_FACTOR_ID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PROG_AF_PTID_TIER_LEVEL] ON [dbo].[PROG_AWARD_FACTOR] ([PROGRESSIVE_TYPE_ID], [TIER_LEVEL]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROG_AWARD_FACTOR] ADD CONSTRAINT [FK_PROG_AWARD_FACTOR_PROGRESSIVE_TYPE] FOREIGN KEY ([PROGRESSIVE_TYPE_ID]) REFERENCES [dbo].[PROGRESSIVE_TYPE] ([PROGRESSIVE_TYPE_ID])
GO
EXEC sp_addextendedproperty N'MS_Description', N'Stores Award Factors by Tier for a Progressive Type. Used to validate progressive win amounts.', 'SCHEMA', N'dbo', 'TABLE', N'PROG_AWARD_FACTOR', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Progressive Jackpot Award Factor', 'SCHEMA', N'dbo', 'TABLE', N'PROG_AWARD_FACTOR', 'COLUMN', N'AWARD_FACTOR'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Row identifer', 'SCHEMA', N'dbo', 'TABLE', N'PROG_AWARD_FACTOR', 'COLUMN', N'PROG_AWARD_FACTOR_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Link to ProgressiveType table', 'SCHEMA', N'dbo', 'TABLE', N'PROG_AWARD_FACTOR', 'COLUMN', N'PROGRESSIVE_TYPE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Tier Level', 'SCHEMA', N'dbo', 'TABLE', N'PROG_AWARD_FACTOR', 'COLUMN', N'TIER_LEVEL'
GO
