CREATE TABLE [dbo].[PLAY_STATS_HOURLY]
(
[PLAY_STATS_HOURLY_ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[LOCATION_ID] [int] NOT NULL,
[MACH_NO] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CASINO_MACH_NO] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACCT_DATE] [datetime] NOT NULL,
[DEAL_NO] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_DEAL_NO] DEFAULT ((0)),
[GAME_CODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DENOM] [smallmoney] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_DENOM] DEFAULT ((0)),
[COINS_BET] [smallint] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_COINS_BET] DEFAULT ((0)),
[LINES_BET] [smallint] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_LINES_BET] DEFAULT ((0)),
[HOUR_OF_DAY] [smallint] NOT NULL,
[PLAY_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_PLAY_COUNT] DEFAULT ((0)),
[LOSS_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_LOSS_COUNT] DEFAULT ((0)),
[WIN_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_WIN_COUNT] DEFAULT ((0)),
[JACKPOT_COUNT] [smallint] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_JACKPOT_COUNT] DEFAULT ((0)),
[FORFEIT_COUNT] [smallint] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_FORFEIT_COUNT] DEFAULT ((0)),
[TICKET_IN_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_TICKET_IN_COUNT] DEFAULT ((0)),
[TICKET_OUT_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_TICKET_OUT_COUNT] DEFAULT ((0)),
[AMOUNT_IN] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_AMOUNT_IN] DEFAULT ((0)),
[AMOUNT_PLAYED] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_AMOUNT_PLAYED] DEFAULT ((0)),
[AMOUNT_LOST] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_AMOUNT_WON1] DEFAULT ((0)),
[AMOUNT_WON] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_AMOUNT_WON] DEFAULT ((0)),
[AMOUNT_JACKPOT] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_AMOUNT_JACKPOT] DEFAULT ((0)),
[AMOUNT_FORFEITED] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_AMOUNT_FORFEITED] DEFAULT ((0)),
[AMOUNT_PROG] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_AMOUNT_PROG] DEFAULT ((0)),
[TICKET_IN_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_TICKET_IN_COUNT1] DEFAULT ((0)),
[TICKET_OUT_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_TICKET_OUT_COUNT1] DEFAULT ((0)),
[PROG_CONTRIBUTION] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_PROG_CONTRIBUTION] DEFAULT ((0)),
[BILL_COUNT_1] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_BILL_COUNT_1] DEFAULT ((0)),
[BILL_COUNT_2] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_BILL_COUNT_2] DEFAULT ((0)),
[BILL_COUNT_5] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_BILL_COUNT_5] DEFAULT ((0)),
[BILL_COUNT_10] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_BILL_COUNT_10] DEFAULT ((0)),
[BILL_COUNT_20] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_BILL_COUNT_20] DEFAULT ((0)),
[BILL_COUNT_50] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_BILL_COUNT_50] DEFAULT ((0)),
[BILL_COUNT_100] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_BILL_COUNT_100] DEFAULT ((0)),
[BILL_COUNT_OTHER] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_BILL_COUNT_OTHER] DEFAULT ((0)),
[PROMO_IN_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_PROMO_IN_AMOUNT] DEFAULT ((0)),
[PROMO_IN_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_PROMO_IN_COUNT] DEFAULT ((0)),
[EFT_IN_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_EFT_IN_AMOUNT] DEFAULT ((0)),
[EFT_IN_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_EFT_IN_COUNT] DEFAULT ((0)),
[EFT_OUT_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_EFT_OUT_AMOUNT] DEFAULT ((0)),
[EFT_OUT_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_EFT_OUT_COUNT] DEFAULT ((0)),
[EFT_PROMO_IN_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_EFT_PROMO_IN_AMOUNT] DEFAULT ((0)),
[EFT_PROMO_IN_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_EFT_PROMO_IN_COUNT] DEFAULT ((0)),
[EFT_PROMO_OUT_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_EFT_PROMO_OUT_AMOUNT] DEFAULT ((0)),
[EFT_PROMO_OUT_COUNT] [int] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_EFT_PROMO_OUT_COUNT] DEFAULT ((0)),
[MAIN_DOOR_OPEN_COUNT] [smallint] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_MAIN_DOOR_OPEN_COUNT] DEFAULT ((0)),
[CASH_DOOR_OPEN_COUNT] [smallint] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_CASH_DOOR_OPEN_COUNT] DEFAULT ((0)),
[LOGIC_DOOR_OPEN_COUNT] [smallint] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_LOGIC_DOOR_OPEN_COUNT] DEFAULT ((0)),
[BASE_DOOR_OPEN_COUNT] [smallint] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_BASE_DOOR_OPEN_COUNT] DEFAULT ((0)),
[AMOUNT_PLAYED_PROMO] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_AMOUNT_PLAYED_PROMO] DEFAULT ((0)),
[AMOUNT_WON_PROMO] [money] NOT NULL CONSTRAINT [DF_PLAY_STATS_HOURLY_AMOUNT_WON_PROMO] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLAY_STATS_HOURLY] ADD CONSTRAINT [PK_PLAY_STATS_HOURLY_1] PRIMARY KEY CLUSTERED  ([PLAY_STATS_HOURLY_ID], [LOCATION_ID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLAY_STATS_HOURLY] ADD CONSTRAINT [IX_PLAY_STATS_HOURLY] UNIQUE NONCLUSTERED  ([MACH_NO], [CASINO_MACH_NO], [ACCT_DATE], [DEAL_NO], [GAME_CODE], [DENOM], [COINS_BET], [LINES_BET], [HOUR_OF_DAY], [LOCATION_ID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Stores summarized play and monetary data by EGM and Accounting Date and Hour.', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Accounting Date', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'ACCT_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total dollars Forfeited (F)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'AMOUNT_FORFEITED'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total dollars deposited (M)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'AMOUNT_IN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total Jackpot dollars won (J)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'AMOUNT_JACKPOT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total loss dollars (L)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'AMOUNT_LOST'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Amount Played in dollars (L,W,F,J)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'AMOUNT_PLAYED'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total Progressive dollars won', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'AMOUNT_PROG'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total normal win dollars won (W)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'AMOUNT_WON'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Casino Machine Number', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'CASINO_MACH_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Coins Bet', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'COINS_BET'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Deal Number', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'DEAL_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Denomination', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'DENOM'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total number of Forfeit Plays (F)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'FORFEIT_COUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Game Code', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'GAME_CODE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Hour of Day', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'HOUR_OF_DAY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total number of Jackpot Plays (J)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'JACKPOT_COUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lines Bet', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'LINES_BET'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Location Identifier', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'LOCATION_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total number of Loss Plays (L)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'LOSS_COUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Machine Number', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'MACH_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total number of Plays (L,W,J,F)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'PLAY_COUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'PK Identity Int', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'PLAY_STATS_HOURLY_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Amount in dollars of Vouchers accepted into the Machine', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'TICKET_IN_AMOUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Number of Vouchers inserted into the Machine', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'TICKET_IN_COUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Amount in dollars of Vouchers printed and dispenses from the Machine', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'TICKET_OUT_AMOUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Number of Vouchers dispensed from the Machine', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'TICKET_OUT_COUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total number of Wins (W)', 'SCHEMA', N'dbo', 'TABLE', N'PLAY_STATS_HOURLY', 'COLUMN', N'WIN_COUNT'
GO
