CREATE TABLE [dbo].[COINS_BET_TO_GAME_TYPE]
(
[COINS_BET] [smallint] NOT NULL,
[GAME_TYPE_CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COINS_BET_TO_GAME_TYPE] ADD CONSTRAINT [PK_COINS_BET_TO_GAME_TYPE] PRIMARY KEY CLUSTERED  ([GAME_TYPE_CODE], [COINS_BET]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COINS_BET_TO_GAME_TYPE] ADD CONSTRAINT [FK_COINS_BET_TO_GAME_TYPE_GAME_TYPE] FOREIGN KEY ([GAME_TYPE_CODE]) REFERENCES [dbo].[GAME_TYPE] ([GAME_TYPE_CODE])
GO
EXEC sp_addextendedproperty N'MS_Description', N'Stores the valid Coins Bet values for Game Types', 'SCHEMA', N'dbo', 'TABLE', N'COINS_BET_TO_GAME_TYPE', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Valid Number of Coins Bet for Game Type', 'SCHEMA', N'dbo', 'TABLE', N'COINS_BET_TO_GAME_TYPE', 'COLUMN', N'COINS_BET'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Game Type Code', 'SCHEMA', N'dbo', 'TABLE', N'COINS_BET_TO_GAME_TYPE', 'COLUMN', N'GAME_TYPE_CODE'
GO
