SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[uvwMachineSetup]
AS
SELECT
   ms.MACH_NO,
   ms.CASINO_MACH_NO,
   ms.MODEL_DESC,
   ms.IP_ADDRESS,
   ms.BALANCE,
   ms.GAME_RELEASE,
   ms.OS_VERSION,
   ms.ACTIVE_FLAG,
   ms.REMOVED_FLAG,
   ms.BANK_NO,
   ms.GAME_CODE,
   ISNULL(gs.GAME_DESC, '<null>')  AS GS_GAME_DESC,
   ISNULL(gs.GAME_TYPE_CODE, '')   AS GS_GTC,
   ISNULL(b.GAME_TYPE_CODE, '')    AS BANK_GTC,
   b.IS_PAPER                      AS BANK_IS_PAPER,
   ISNULL(b.BANK_DESCR, '<null>')  AS BANK_DESC,
   ISNULL(gt.LONG_NAME, '<null>')  AS GT_LONG_NAME,
   ISNULL(gs.TYPE_ID, '')          AS GS_TYPE_ID,
   ISNULL(gt.TYPE_ID, '')          AS GT_TYPE_ID,
   gt.PRODUCT_ID                   AS GT_PRODUCT_ID,
   gt.MAX_COINS_BET                AS GT_MAX_COINS_BET,
   gt.MAX_LINES_BET                AS GT_MAX_LINES_BET,
   gt.MULTI_BET_DEALS              AS GT_MULTI_BET_DEALS,
   gt.SHOW_PAY_CREDITS             AS GT_SHOW_PAY_CREDITS,
   gt.PROGRESSIVE_TYPE_ID          AS GT_PROGRESSIVE_TYPE_ID
FROM MACH_SETUP ms
   LEFT OUTER JOIN BANK        b ON ms.BANK_NO = b.BANK_NO
   LEFT OUTER JOIN GAME_SETUP gs ON ms.GAME_CODE = gs.GAME_CODE
   LEFT OUTER JOIN GAME_TYPE  gt ON gs.GAME_TYPE_CODE = gt.GAME_TYPE_CODE

GO
