SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[uvwCasinoTrans]
AS
SELECT
   ct.TRANS_NO,
   ct.CAS_ID,
   ct.LOCATION_ID,
   ct.DEAL_NO,
   ct.MACH_NO,
   ms.CASINO_MACH_NO,
   ct.ROLL_NO,
   ct.TICKET_NO,
   ct.DENOM,
   ct.TRANS_AMT,
   ct.BARCODE_SCAN,
   ct.TRANS_ID,
   tr.SHORT_NAME AS TRANS_TYPE,
   tc.SHORT_NAME AS TRANS_CATEGORY,
   tc.TRANS_CATEGORY_ID,
   ds.TYPE_ID    AS DEAL_TYPE_ID,
   ct.DTIMESTAMP,
   ct.ACCT_DATE,
   ct.MODIFIED_BY,
   ct.CARD_ACCT_NO,
   ct.BALANCE,
   ct.GAME_CODE,
   ct.COINS_BET,
   ct.LINES_BET,
   ct.TIER_LEVEL,
   ct.PRODUCT_ID,
   ct.PRESSED_COUNT
FROM CASINO_TRANS ct
   LEFT OUTER JOIN TRANS          tr ON ct.TRANS_ID = tr.TRANS_ID
   LEFT OUTER JOIN TRANS_CATEGORY tc ON tr.TRANS_CATEGORY_ID = tc.TRANS_CATEGORY_ID
   LEFT OUTER JOIN MACH_SETUP     ms ON ct.MACH_NO = ms.MACH_NO
   LEFT OUTER JOIN DEAL_SETUP     ds ON ct.DEAL_NO = ds.DEAL_NO
GO
