SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[uvwPoolEvents]
AS
SELECT
   pe.POOL_EVENT_ID,
   pe.POOL_EVENT_TYPE_ID,
   pet.LONG_NAME AS EVENT_NAME,
   pe.PROGRESSIVE_POOL_ID,
   pe.POOL_NUMBER,
   pe.POOL_EVENT_DATE_TIME,
   pe.ACCT_DATE,
   pe.AMOUNT
FROM dbo.POOL_EVENT pe
   JOIN dbo.POOL_EVENT_TYPE pet ON pe.POOL_EVENT_TYPE_ID = pet.POOL_EVENT_TYPE_ID
GO
