SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[uvwMachineGameCodes]
AS
SELECT
   ms.MACH_NO,
   ms.CASINO_MACH_NO,
   ms.MODEL_DESC,
   gs.GAME_DESC AS GameDesc,
   ms.GAME_CODE,
   ms.BANK_NO,
   ms.ACTIVE_FLAG,
   ms.GAME_RELEASE,
   ms.OS_VERSION,
   ms.IP_ADDRESS,
   ms.MACH_SERIAL_NO,
   ms.BALANCE
FROM MACH_SETUP AS ms
   JOIN GAME_SETUP AS gs ON ms.GAME_CODE = gs.GAME_CODE
WHERE  (ms.REMOVED_FLAG = 0)
GO
