SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[uvwDealStats]
AS
SELECT
   dstats.DEAL_NO,
   dset.DEAL_DESCR AS DEAL_DESC,
   dset.TAB_AMT,
   dset.IS_OPEN,
   cf.FORM_NUMB,
   dstats.PLAY_COUNT,
   cf.TABS_PER_DEAL,
   cf.WINS_PER_DEAL, 
   dstats.WIN_COUNT,
   dstats.JACKPOT_COUNT AS JACKPOTS_HIT,
   cf.JACKPOT_COUNT     AS JACKPOTS_PER_DEAL,
   cf.GAME_TYPE_CODE,
   gt.PRODUCT_ID,
   cf.DENOMINATION,
   cf.COINS_BET,
   cf.LINES_BET,
   cf.TOTAL_AMT_OUT,
   dstats.BASE_AMOUNT_WON
FROM dbo.DEAL_STATS dstats
   JOIN dbo.DEAL_SETUP dset ON dstats.DEAL_NO = dset.DEAL_NO
   JOIN dbo.CASINO_FORMS cf ON dset.FORM_NUMB = cf.FORM_NUMB
   JOIN dbo.GAME_TYPE gt ON cf.GAME_TYPE_CODE = gt.GAME_TYPE_CODE
GO
