//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class POSResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal POSResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS.Core.POSResources", typeof(POSResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cash.
        /// </summary>
        public static string AddCashTitle {
            get {
                return ResourceManager.GetString("AddCashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving this screen will end your current session.  Are you sure you want to end this session?.
        /// </summary>
        public static string AreYouSureEndSessionMsg {
            get {
                return ResourceManager.GetString("AreYouSureEndSessionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this item from the transaction?.
        /// </summary>
        public static string AreYouSureRemoveTransactionItemMsg {
            get {
                return ResourceManager.GetString("AreYouSureRemoveTransactionItemMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Void Transaction?  This transaction will be cleared..
        /// </summary>
        public static string AreYouSureVoidTransactionMsg {
            get {
                return ResourceManager.GetString("AreYouSureVoidTransactionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode is required..
        /// </summary>
        public static string BarcodeRequiredMsg {
            get {
                return ResourceManager.GetString("BarcodeRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount to remove is greater than the current balance..
        /// </summary>
        public static string CashDrawerCannotRemoveGreaterThanBalanceMsg {
            get {
                return ResourceManager.GetString("CashDrawerCannotRemoveGreaterThanBalanceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an amount and password..
        /// </summary>
        public static string CashDrawerPromptAmountPasswordMsg {
            get {
                return ResourceManager.GetString("CashDrawerPromptAmountPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Drawer Starting Balance.
        /// </summary>
        public static string CashDrawerStartingBalanceTitle {
            get {
                return ResourceManager.GetString("CashDrawerStartingBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Drawer.
        /// </summary>
        public static string CashDrawerTitle {
            get {
                return ResourceManager.GetString("CashDrawerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Action.
        /// </summary>
        public static string ConfirmActionTitle {
            get {
                return ResourceManager.GetString("ConfirmActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not receive approval.
        /// </summary>
        public static string DidNotGetApprovalMsg {
            get {
                return ResourceManager.GetString("DidNotGetApprovalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not receive approval to reprint this receipt..
        /// </summary>
        public static string DidNotGetApprovalReprintMsg {
            get {
                return ResourceManager.GetString("DidNotGetApprovalReprintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout failure.  Supervisor authorization is required for one or more vouchers.  Please try again..
        /// </summary>
        public static string DidNotGetPayoutApprovalMsg {
            get {
                return ResourceManager.GetString("DidNotGetPayoutApprovalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a Cash Drawer attached to this workstation?.
        /// </summary>
        public static string IsCashDrawerAttachedMsg {
            get {
                return ResourceManager.GetString("IsCashDrawerAttachedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Printed Receipt.
        /// </summary>
        public static string LastPrintedReceiptTitle {
            get {
                return ResourceManager.GetString("LastPrintedReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred getting last receipt information..
        /// </summary>
        public static string LastReceiptErrorMsg {
            get {
                return ResourceManager.GetString("LastReceiptErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Default Retail Location found. Correct immediately!.
        /// </summary>
        public static string NoDefaultLocationFoundMsg {
            get {
                return ResourceManager.GetString("NoDefaultLocationFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Default Retail Location Configured.
        /// </summary>
        public static string NoDefaultLocationFoundTitle {
            get {
                return ResourceManager.GetString("NoDefaultLocationFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Last Receipt Found..
        /// </summary>
        public static string NoLastReceiptFoundMsg {
            get {
                return ResourceManager.GetString("NoLastReceiptFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No printers have been detected.  Please ensure you are connected to a printer and try again..
        /// </summary>
        public static string NoPrintersDetectedMsg {
            get {
                return ResourceManager.GetString("NoPrintersDetectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout Station.
        /// </summary>
        public static string PayoutStationTitle {
            get {
                return ResourceManager.GetString("PayoutStationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout Transaction Successful..
        /// </summary>
        public static string PayoutSuccessfulMsg {
            get {
                return ResourceManager.GetString("PayoutSuccessfulMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt printer is not available or configured..
        /// </summary>
        public static string PrinterNotAvailableMsg {
            get {
                return ResourceManager.GetString("PrinterNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Not Setup or Available.
        /// </summary>
        public static string PrinterNotSetupOrAvailableTitle {
            get {
                return ResourceManager.GetString("PrinterNotSetupOrAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Settings successfully saved..
        /// </summary>
        public static string PrinterSettingsSavedMsg {
            get {
                return ResourceManager.GetString("PrinterSettingsSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Settings.
        /// </summary>
        public static string PrinterSettingsTitle {
            get {
                return ResourceManager.GetString("PrinterSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Cash.
        /// </summary>
        public static string RemoveCashTitle {
            get {
                return ResourceManager.GetString("RemoveCashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Payouts have been disabled.  Please contact your supervisor..
        /// </summary>
        public static string SitePayoutsDisabledMsg {
            get {
                return ResourceManager.GetString("SitePayoutsDisabledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Payouts Disabled.
        /// </summary>
        public static string SitePayoutsDisabledTitle {
            get {
                return ResourceManager.GetString("SitePayoutsDisabledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Balance was not set..
        /// </summary>
        public static string StartingBalanceNotSetMsg {
            get {
                return ResourceManager.GetString("StartingBalanceNotSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue you must enter a starting balance greater than 0 and less than or equal to $250,000..
        /// </summary>
        public static string StartingBalanceValidationMsg {
            get {
                return ResourceManager.GetString("StartingBalanceValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor approval is required to proceed..
        /// </summary>
        public static string SupervisorApprovalRequiredMsg {
            get {
                return ResourceManager.GetString("SupervisorApprovalRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Approval.
        /// </summary>
        public static string SupervisorApprovalTitle {
            get {
                return ResourceManager.GetString("SupervisorApprovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to scan voucher.  You cannot exceed 25 vouchers in a transaction..
        /// </summary>
        public static string TooManyVouchersInTransactionMsg {
            get {
                return ResourceManager.GetString("TooManyVouchersInTransactionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount to pay exceeds the cash drawer balance.  Please add cash to the cash drawer and try again..
        /// </summary>
        public static string TotalPayoutExceedsCashDrawerMsg {
            get {
                return ResourceManager.GetString("TotalPayoutExceedsCashDrawerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Payout Transaction.
        /// </summary>
        public static string UnableToPayoutTitle {
            get {
                return ResourceManager.GetString("UnableToPayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Password are required..
        /// </summary>
        public static string UsernamePasswordRequiredMsg {
            get {
                return ResourceManager.GetString("UsernamePasswordRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user does not have permission to approve vouchers..
        /// </summary>
        public static string UserNotPermittedVouchersMsg {
            get {
                return ResourceManager.GetString("UserNotPermittedVouchersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher has already been redeemed..
        /// </summary>
        public static string VoucherAlreadyRedeemedMsg {
            get {
                return ResourceManager.GetString("VoucherAlreadyRedeemedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher data not found..
        /// </summary>
        public static string VoucherDataNotFoundMsg {
            get {
                return ResourceManager.GetString("VoucherDataNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Detail.
        /// </summary>
        public static string VoucherDetailTitle {
            get {
                return ResourceManager.GetString("VoucherDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher amount exceeds the cash drawer balance.  Please add cash to the cash drawer and try again..
        /// </summary>
        public static string VoucherExceedsCashDrawerMsg {
            get {
                return ResourceManager.GetString("VoucherExceedsCashDrawerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher is expired..
        /// </summary>
        public static string VoucherExpiredMsg {
            get {
                return ResourceManager.GetString("VoucherExpiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher has an invalid checksum value.  Please call the supervisor..
        /// </summary>
        public static string VoucherInvalidChecksumMsg {
            get {
                return ResourceManager.GetString("VoucherInvalidChecksumMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackpot voucher exceeds the payout threshold..
        /// </summary>
        public static string VoucherJackpotExceedsThresholdMsg {
            get {
                return ResourceManager.GetString("VoucherJackpotExceedsThresholdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackpot winner vouchers must be cashed individually.  Please complete your current transaction and try again..
        /// </summary>
        public static string VoucherJackpotIndividualCashoutMsg {
            get {
                return ResourceManager.GetString("VoucherJackpotIndividualCashoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher is a Non-Cashable Promotional Voucher..
        /// </summary>
        public static string VoucherNonCashableMsg {
            get {
                return ResourceManager.GetString("VoucherNonCashableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher is not in a valid state.  Please call supervisor..
        /// </summary>
        public static string VoucherNotValidMsg {
            get {
                return ResourceManager.GetString("VoucherNotValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher amount is too small for cashout..
        /// </summary>
        public static string VoucherTooSmallMsg {
            get {
                return ResourceManager.GetString("VoucherTooSmallMsg", resourceCulture);
            }
        }
    }
}
