SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/*
--------------------------------------------------------------------------------
User Stored Procedure tpTransL

Created 04-11-2003 by Chris Coddington

Desc: Handles all losing transactions.

Return values: ErrorCode, ErrorDescription, ShutdownFlag

Called by: Transaction Portal

Parameters:
   @Barcode             Barcode of the Ticket
   @CardAccount         Card Account Number in Machine
   @CoinsBet            Number of Coins Bet
   @CoinsWon            Number of Coins Won
   @DealNumber          Deal Number of the Ticket
   @LinesBet            Number of Lines Bet
   @MachineBalance      New Balance that the Machine calculated
   @MachineDenomination Denomination of the Play
   @MachineNumber       The Machine number played
   @MachineSequence     Transaction sequence number generated by the TransPortal
   @RollNo              Roll number of the Ticket
   @TicketNumber        Ticket Number played
   @TierLevel           Tier Level of the win (0 in this case)
   @TimeStamp           DateTime from the machine (overwritten by this procedure).
   @PressUpCount        Number of times player pressed up their bet (for the Press It Up Poker game)
   @PromoBalance        Promotional Balance that the Machine calculated


Change Log:
Changed By    Date           Database Version
  Change Description
--------------------------------------------------------------------------------
Chris C.      12-15-2003
  Move Deal_Stats and Daily_Deal_Stats logic out of the error checking area.

Chris C.      02-10-2004
  Changed float datatypes to money datatypes.

Terry Watkins 02-20-2004
  Added insert into MACHINE_STATS.
  Added insertion of the Game Code of the Machine into CASINO_TRANS.

Chris C.      04-22-2004
  Changed duplicate ticket test to send back the last ack when sequence number
  and balance are the same.

Chris C.      05-05-2004
  Modified tpInsertCasinoTrans to accept denom.

Terry Watkins 07-08-2004
  Changed datatype of @MachineDenom from SmallMoney to Money to fix arithmetic
  overflow bug when calculating @BaseTrans and @TabCost with large @CoinsWon
  values. (Not really necessary in this routine but changed to be consistant
  with tpTrans(FJW).

Terry Watkins 10-25-2004     v3.6.5
  Added update of new CARD_ACCT.PROMO_AMOUNT column.

Terry Watkins 11-04-2004     v4.0.0
  Added insertion of TransID into CASINO_TRANS.
  Added Cardless play handling.

Terry Watkins 01-13-2005     v4.0.1
  Added code to update new MACHINE_METER table.
  Added argument @PressUpCount to support new Press It Up Poker game.

A. Murthy     01-26-2005     v4.0.1
  For TITO set @CardAccount = 'INTERNAL'.

Terry Watkins 03-31-2005     v4.0.2
  Moved deactivation of eDeal ticket from tpTransT to tpTransL,W,J,and F.

Terry Watkins 05-10-2005     v4.1.1
  Added promotional coupon (eCoupon) handling:
    - Added argument @PromoBalance
    - Added logic to exhaust promotional balance before reducing machine or
      card account balance.

Terry Watkins 06-20-2005      v4.1.4
  Changed size of @CardAccount from 16 to 20.
  Added support for Keno - Balance checking validation.
  The TabCost calculation for keno is different than the other games.

Terry Watkins 07-25-2005      v4.1.7
  Fixed error that did not set @NewBalance = @Balance when
  @SystemPromoBal >= @TabCost (~line 379).

Terry Watkins 09-07-2005     v4.2.4
  Changed the value inserted into CASINO_TRANS.BALANCE to be the total of the
  account balance plus the promo balance.

Terry Watkins 01-18-2006     v5.0.1
  Added retrieval of GameClass which is passed to tpDeactivateTicket so the
  ticket in the proper database (eDeal or eTab) is deactivated.

  Modified update to MACH_SETUP.ACTIVE_FLAG so that on error, the flag is set
  to 0 only if it is currently set to 1 (data type changed from Bit to TinyInt).

  Added ISNULL check to update of BANK.PROG_AMT for progressive deals.

Terry Watkins 01-18-2006     v5.0.2
  Added logic to update or insert a row into DEAL_INVENTORY if playing from a
  Paper Deal.

  Modified progressive pool contribution amount to be the Tab Amount * the
  Progressive % (was Machine Denom * Progressive %)

  Removed code that updated DAILY_DEAL_STATS.  That table is no longer used.

Terry Watkins 01-18-2006     v5.0.5
  Added logic to replace the Roll number sent from the machine with a calculated
  Roll number if playing from a Paper Deal.

Terry Watkins 10-04-2006     v5.0.8
  Added code to update new MACHINE_PLAY_STATS table.
  
  Removed @TicketStatusID. No longer needed because column
  CASINO_TRANS.TICKET_STATUS_ID has been removed.

A. Murthy     08-21-2007     v6.0.1
  For Bingo play, do NOT call tpDeactivateTicket

Terry Watkins 01-24-2008     v6.0.2
  Change data type of @ProgressivePct from Int to Decimal(6,4)

Terry Watkins 07-21-2008     v7.0.0
  Added Progressive support.
  
  Uses new function dbo.ufnGetAcctDate() to retrieve the accounting date.
  
  @AcctDate changed from VarChar(16) to DateTime.
  
  Added code to disallow balance adjustments that exceed the value set in
  CASINO.MAX_BAL_ADJUSTMENT.

Terry Watkins 07-22-2008     v7.1.0
  Added EXEC of new sp tpUpdatePoolContribution which records progressive pool
  contributions by accounting date to each pool.

Terry Watkins 05-12-2010     v7.2.1
  Modified insert into CASINO_EVENT_LOG to update new columns ERROR_NO and
  MACH_NO.

Terry Watkins 10-15-2010     v7.2.4
  Added the recording of tab errors in the TAB_ERROR table if playing a paper
  game.

Terry Watkins 11-11-2010     DCLottery v1.0.0
  Added retrieval of @LocationID to support addition of column
  CASINO_TRANS.LOCATION_ID
  Added insertion into (or updating of) table PLAY_STATS_HOURLY.

Aldo Zamora 04-22-2013     Lottery Retail v3.1.0
  Added LocationID WHEN updating the TabError table.
  
Louis Epstein 10-25-2013     v3.1.6
  Added machine timestamp functionality
  
Louis Epstein 12-23-2013     v3.1.7
  Added promo credits functionality
  
Louis Epstein 01-22-2014     v3.1.8
  Corrected promo credits calculation
  
Eloy Bencomo 03-04-2014      v3.1.9
  Added TicketNumber Logging to TAB_ERROR
  
Louis Epstein 04-10-2014     v3.2.1
  Added functionality to contribute to multi level progressive pools
  
Louis Epstein 06-18-2014     v3.2.3
  Modified stat recording functionality to use tpUpdatePlayStatsHourlyAndDaily
--------------------------------------------------------------------------------
*/
CREATE PROCEDURE [dbo].[tpTransL]
   @Barcode             VarChar(128),
   @CardAccount         VarChar(20),
   @CoinsBet            Int,
   @CoinsWon            Int,
   @DealNumber          Int,
   @LinesBet            Int,
   @MachineBalance      Int,
   @MachineDenomination Int,
   @MachineNumber       VarChar(5),
   @MachineSequence     Int,
   @RollNo              Int,
   @TicketNumber        Int,
   @TierLevel           SmallInt,
   @TimeStamp           DateTime,
   @PressUpCount        SmallInt,
   @PromoBalance        Int = 0
AS

-- Variable Declarations
DECLARE @AcctDate           DateTime
DECLARE @Balance            Money
DECLARE @BankNumber         Int
DECLARE @CardRequired       Bit
DECLARE @CasinoID           VarChar(6)
DECLARE @CasinoMachNo       VarChar(8)
DECLARE @CasinoTransID      Int
DECLARE @DealNo             Int
DECLARE @DealTypeCode       Char(1)
DECLARE @Debug              Bit
DECLARE @ErrorDescription   VarChar(256)
DECLARE @ErrorID            Int
DECLARE @ErrorNum           Int
DECLARE @ErrorSource        VarChar(64)
DECLARE @ErrorText          VarChar(1024)
DECLARE @ErrorTypeID        Int
DECLARE @EventCode          VarChar(2)
DECLARE @EventLogDesc       VarChar(1024)
DECLARE @GameClass          SmallInt
DECLARE @GameTypeCode       VarChar(2)
DECLARE @HourOfDay          Int
DECLARE @IsActive           Bit
DECLARE @IsBingo            Bit
DECLARE @IsPaper            Bit
DECLARE @IsProgressive      Bit
DECLARE @IsPromoOn          Bit
DECLARE @LastBalance        Int
DECLARE @LocationID         Int
DECLARE @LockupMachine      Int
DECLARE @MachGameCode       Char(3)
DECLARE @MachNbrAsInt       Int
DECLARE @MachineBal         Money
DECLARE @MachineDenom       Money
DECLARE @MachinePromoBal    Money
DECLARE @MachPromoBalPrePlay Money
DECLARE @MachNo             VarChar(5)
DECLARE @MaxBalAdjust       Money
DECLARE @MsgText            VarChar(2048)
DECLARE @NewBalance         Money
DECLARE @PlayStatsHourlyID  Int
DECLARE @PRate1             Decimal(9,8)
DECLARE @PRate2             Decimal(9,8)
DECLARE @PRate3             Decimal(9,8)
DECLARE @PRateCombined      Decimal(9,8)
DECLARE @ProductLineID      SmallInt
DECLARE @ProgContribution   Money
DECLARE @ProgressiveTypeID  Int
DECLARE @PromoAmount        SmallMoney
DECLARE @PromoAmountPlayed  SmallMoney
DECLARE @ReturnCode         Int
DECLARE @SaveTrans          Int
DECLARE @SequenceNum        Int
DECLARE @SummarizePlay      Bit
DECLARE @SystemPromoBal     Money
DECLARE @TabCost            SmallMoney
DECLARE @TabsPerSubset      Int
DECLARE @TestPromoAmount    Money
DECLARE @TicketNo           Int
DECLARE @TotalCoinsBet      Int
DECLARE @TransAmt           Money
DECLARE @TransID            SmallInt
DECLARE @MachineTimeStamp   DateTime

SET NOCOUNT ON

-- Variable Initialization
-- Convert balance and denom first, other vars depend on them...
SET @MachineBal      = CONVERT(Money, @MachineBalance) / 100
SET @MachineDenom    = CONVERT(Money, @MachineDenomination) / 100
SET @MachinePromoBal = CONVERT(Money, @PromoBalance) / 100

SET @MachineTimeStamp   = @TimeStamp
SET @Balance            = 0
SET @CardRequired       = 1
SET @DealNo             = @DealNumber
SET @DealTypeCode       = ' '
SET @ErrorID            = 0
SET @ErrorDescription   = ''
SET @ErrorSource        = 'tpTransL Stored Procedure'
SET @ErrorText          = ''
SET @ErrorTypeID        = 0
SET @EventCode          = 'SP'
SET @GameClass          = 2
SET @GameTypeCode       = ''
SET @EventLogDesc       = ''
SET @IsActive           = 0
SET @IsBingo            = 0
SET @IsPaper            = 0
SET @IsProgressive      = 0
SET @IsPromoOn          = 0
SET @LocationID         = 0
SET @LockupMachine      = 0
SET @MachNbrAsInt       = CAST(@MachineNumber AS Int)
SET @NewBalance         = 0
SET @PRateCombined      = 0
SET @ProductLineID      = 0
SET @ProgContribution   = 0
SET @ProgressiveTypeID  = 0
SET @PromoAmount        = 0
SET @PromoAmountPlayed  = 0
SET @ReturnCode         = 0
SET @SaveTrans          = 2
SET @SystemPromoBal     = 0
SET @TabsPerSubset      = 0
SET @TestPromoAmount    = 0
SET @TicketNo           = @TicketNumber
SET @TotalCoinsBet      = @CoinsBet
SET @TransAmt           = 0
SET @TransID            = 10
SET @TimeStamp          = GetDate()

-- Check Debug mode...
SELECT @Debug = ISNULL(DEBUG_MODE, 0) FROM DEBUG_SETTING WHERE DEBUG_ENTITY = 'tpTransL'

-- If Debug mode, save argument values...
IF (@Debug = 1)
   -- Record argument values.
   BEGIN
      SET @MsgText =
         'tpTransL Argument Values:  ' + 
         '  Barcode: '             + ISNULL(@Barcode, '<null>') +
         '  CardAccount: '         + ISNULL(@CardAccount, '<null>') +
         '  CoinsBet: '            + ISNULL(CAST(@CoinsBet AS VarChar), '<null>') +
         '  CoinsWon: '            + ISNULL(CAST(@CoinsWon AS VarChar), '<null>') +
         '  DealNumber: '          + ISNULL(CAST(@DealNumber AS VarChar), '<null>') +
         '  LinesBet: '            + ISNULL(CAST(@LinesBet AS VarChar), '<null>') +
         '  MachineBalance: '      + ISNULL(CAST(@MachineBalance AS VarChar), '<null>') +
         '  MachineDenomination: ' + ISNULL(CAST(@MachineDenomination AS VarChar), '<null>') +
         '  MachineNumber: '       + ISNULL(@MachineNumber, '<null>') +
         '  MachineSequence: '     + ISNULL(CAST(@MachineSequence AS VarChar), '<null>') +
         '  RollNo: '              + ISNULL(CAST(@RollNo AS VarChar), '<null>') +
         '  TicketNumber: '        + ISNULL(CAST(@TicketNumber AS VarChar), '<null>') +
         '  TierLevel: '           + ISNULL(CAST(@TierLevel AS VarChar), '<null>') +
         '  PressUpCount: '        + ISNULL(CAST(@PressUpCount AS VarChar), '<null>') +
         '  PromoBalance: '        + ISNULL(CAST(@PromoBalance AS VarChar), '<null>')
      
      EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
   END

-- Retrieve CASINO information.
SELECT
   @CasinoID      = CAS_ID,
   @CardRequired  = PLAYER_CARD,
   @IsPromoOn     = PROMOTIONAL_PLAY,
   @SummarizePlay = SUMMARIZE_PLAY,
   @MaxBalAdjust  = MAX_BAL_ADJUSTMENT,
   @LocationID    = LOCATION_ID
FROM CASINO
WHERE SETASDEFAULT = 1

-- If @CardRequired is 0 (TITO), set @CardAccount to 'INTERNAL'
IF (@CardRequired = 0)
   SET @CardAccount = 'INTERNAL'

-- If Card Account is null or empty, set it to 'INVALID'.
IF (ISNULL(@CardAccount, '') = '')
   SET @CardAccount = 'INVALID'

-- Get Current Accounting Date and hour of the day...
SET @AcctDate  = dbo.ufnGetAcctDate()
SET @HourOfDay = dbo.ufnCurrentHour()

-- Check for existance, active, removed status of machine.
SET @ErrorID = dbo.GetMachineStatus(@MachineNumber)

-- If the MACH_SETUP row was found, retrieve Machine information.
IF (@ErrorID <> 104)
   SELECT
      @CasinoMachNo      = ms.CASINO_MACH_NO,
      @MachGameCode      = ms.GAME_CODE,
      @BankNumber        = ms.BANK_NO,
      @Balance           = ms.BALANCE,
      @SystemPromoBal    = ms.PROMO_BALANCE,
      @GameTypeCode      = gt.GAME_TYPE_CODE,
      @DealTypeCode      = ISNULL(gt.TYPE_ID, ' '),
      @ProgressiveTypeID = gt.PROGRESSIVE_TYPE_ID,
      @GameClass         = pl.GAME_CLASS,
      @ProductLineID     = pl.PRODUCT_LINE_ID
   FROM MACH_SETUP ms
      JOIN BANK          b ON ms.BANK_NO = b.BANK_NO
      JOIN PRODUCT_LINE pl ON b.PRODUCT_LINE_ID = pl.PRODUCT_LINE_ID
      JOIN GAME_TYPE    gt ON b.GAME_TYPE_CODE = gt.GAME_TYPE_CODE
   WHERE MACH_NO = @MachineNumber

-- Is this a progressive game?
IF (@ErrorID = 0 AND @ProgressiveTypeID <> 0)
   -- Yes, so get progressive info...
   BEGIN
      -- Set the progressive flag.
      SET @IsProgressive = 1
      
      -- Retrieve ProgressiveType data...
      SELECT
@PRateCombined = SUM(Rate1) + SUM(Rate2) + SUM(Rate3)
FROM PROGRESSIVE_POOL
WHERE PROGRESSIVE_TYPE_ID = @ProgressiveTypeID AND DENOMINATION = @MachineDenomination
GROUP BY PROGRESSIVE_TYPE_ID, DENOMINATION
   END

-- Set Bingo Machine Flag
IF (@ProductLineID = 7)
   SET @IsBingo = 1

-- Deactive the ticket in the eDeal database ONLY if no error yet and NOT BINGO.
IF (@ErrorID = 0 AND @IsBingo <> 1)
   BEGIN
      EXEC @ErrorNum = tpDeactivateTicket @DealNumber, @TicketNumber, @GameClass
      IF (@Debug = 1)
         BEGIN
            SET @MsgText = 'tpTransL tpDeactivateTicket returned:  ' + ISNULL(CAST(@ErrorNum AS VarChar), '<null>')
            EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
         END
   END

SET @ErrorNum = 0

IF @DealTypeCode <> 'K'
   -- Non-Keno game.
   BEGIN
      SET @TabCost   = @MachineDenom * @CoinsBet * @LinesBet
      IF (@PressUpCount > 0)
         BEGIN
            SET @TabCost = (@TabCost * (@PressUpCount + 1))
            SET @TotalCoinsBet = (@TotalCoinsBet * (@PressUpCount + 1))
         END
   END
ELSE
   -- Keno game.
   BEGIN
      SET @TabCost = @MachineDenom * @CoinsBet
   END

-- Reset the Promotional Amount that will be added to
-- CARD_ACCT.PROMO_AMOUNT if CASINO.PROMOTIONAL_PLAY is set.
IF (@IsPromoOn = 1)
   SET @PromoAmount = @TabCost

-- Is a Card required for Game Play?
IF (@ErrorID = 0 AND @CardRequired = 1)
   BEGIN
      -- Yes, so retrieve Balance and Machine number from the CARD_ACCT table.
      -- Note that for Cardless play, we already have the balance from Machine (line 205).
      SELECT
         @MachNo  = MACH_NO,
         @Balance = BALANCE
      FROM CARD_ACCT
      WHERE CARD_ACCT_NO = @CardAccount
      
      -- Did we find the CARD_ACCT row?
      IF (@@ROWCOUNT = 0)
         -- Card does not exist.
         SET @ErrorID = 102
      ELSE IF (@MachNo <> @MachineNumber)
         -- Card Account machine number does not match incoming machine number.
         SET @ErrorID = 108
   END

-- Has an error been encountered?
IF (@ErrorID = 0)
   BEGIN
      -- No, so update MACH_SETUP.LAST_ACTIVITY...
      UPDATE MACH_SETUP SET LAST_ACTIVITY = @TimeStamp WHERE MACH_NO = @MachineNumber
      
      -- Retrieve Deal info...
      SELECT
         @IsActive       = ds.IS_OPEN,
         @IsPaper        = cf.IS_PAPER,
         @TabsPerSubset  = ds.TABS_PER_ROLL
      FROM DEAL_SETUP ds
         JOIN CASINO_FORMS cf ON ds.FORM_NUMB = cf.FORM_NUMB
      WHERE ds.DEAL_NO = @DealNo
      
      -- Test that the deal exists.
      IF (@@ROWCOUNT > 0)
         BEGIN
            -- For paper Deals, we will replace the Roll Number sent from the machine with a calculated value.
            IF (@IsPaper = 1) SET @RollNo = dbo.GetRollNumber(@TicketNumber, @TabsPerSubset)
            
            DECLARE @DealNum     Int
            DECLARE @RollNum     Int
            DECLARE @TicketNum   Int
            DECLARE @BarcodeScan VarChar(128)
            DECLARE @Coins       Int
            DECLARE @Lines       Int
            
            -- Place last play information into table.
            UPDATE MACH_LAST_PLAY SET
               @DealNum       = DEAL_NO,
               @RollNum       = ROLL_NO,
               @TicketNum     = TICKET_NO,
               @BarcodeScan   = BARCODE_SCAN,
               @Coins         = COINS_BET,
               @Lines         = LINES_BET,
               @SequenceNum   = SEQUENCE_NO,
               @LastBalance   = BALANCE,
               @ErrorNum      = ERROR_NO,
               DEAL_NO        = @DealNumber,
               ROLL_NO        = @RollNo,
               TICKET_NO      = @TicketNumber,
               BARCODE_SCAN   = @Barcode,
               COINS_BET      = @CoinsBet,
               LINES_BET      = @LinesBet,
               ERROR_NO       = 0,
               SEQUENCE_NO    = @MachineSequence,
               BALANCE        = @MachineBalance,
               DTIMESTAMP     = @TimeStamp
            WHERE MACH_NO     = @MachineNumber
            
            -- Machine doesn't exist in table, so insert a record.
            IF (@@ROWCOUNT = 0)
               BEGIN
                  INSERT INTO MACH_LAST_PLAY
                     (MACH_NO, DEAL_NO, ROLL_NO, TICKET_NO, BARCODE_SCAN, COINS_BET,
                      LINES_BET, ERROR_NO, SEQUENCE_NO, BALANCE, DTIMESTAMP)
                  VALUES
                     (@MachineNumber, @DealNumber, @RollNo, @TicketNumber, @Barcode, @CoinsBet,
                      @LinesBet, 0, @MachineSequence, @MachineBalance, @TimeStamp)
                  
                  SET @DealNum = 0
                  SET @TicketNum = 0
               END
            
            -- Is this play the same as the last play?
            IF (@IsBingo = 1) OR NOT((@DealNum = @DealNumber) AND (@TicketNum = @TicketNumber))
               BEGIN
                  -- No, so test that the deal is open.
                  IF (@IsActive = 1)
                     BEGIN
                        -- Update or Insert into DEAL_INVENTORY if playing a Paper Deal...
                        IF (@IsPaper = 1)
                           BEGIN
                              -- Attempt an update.
                              UPDATE DEAL_INVENTORY SET
                                 PLAY_COUNT = PLAY_COUNT + 1,
                                 LAST_PLAY = @TimeStamp
                              WHERE
                                 DEAL_NO = @DealNumber    AND
                                 ROLL_NO = @RollNo        AND
                                 MACH_NO = @MachineNumber
                              -- Was a row updated?
                              IF (@@ROWCOUNT = 0)
                                 INSERT INTO DEAL_INVENTORY
                                    (DEAL_NO, ROLL_NO, MACH_NO, PLAY_COUNT, FIRST_PLAY, LAST_PLAY)
                                 VALUES
                                    (@DealNumber, @RollNo, @MachineNumber, 1, @TimeStamp, @TimeStamp)
                           END
                        
                        -- Make balance change and update promo amount.
                        -- (per Norm - it is okay to adjust the balance without checking the denom first).
                        
                        -- See if the PROMO_BALANCE should be adjusted.
                        SET @TestPromoAmount = (@SystemPromoBal - @TabCost)
                        IF (@TestPromoAmount >= 0 AND @TestPromoAmount <> @MachinePromoBal)
                           BEGIN
                              IF (@MachinePromoBal - @TestPromoAmount <= @MaxBalAdjust)
                                 BEGIN
                                    -- Adjust the server Promo amount (changed 12-08-11)
                                    -- Calculate what the promo balance on the egm was before the play.
                                    SET @MachPromoBalPrePlay = @MachinePromoBal + @TabCost

                                    -- Perform the Promo adjustment.
                                    EXEC @ReturnCode = tpAdjustMachinePromoBalance
                                         @MachineNumber, @CardRequired, @MachPromoBalPrePlay, @SystemPromoBal, 'tpTransL',
                                         @TimeStamp, @CasinoID, @AcctDate, @MachGameCode, @LocationID

                                    IF (@Debug = 1)
                                       BEGIN
                                          SET @MsgText = 'tpTransL executed tpAdjustMachinePromoBalance: ReturnCode = ' + 
                                                         ISNULL(CAST(@ReturnCode AS VarChar), '<null>') +
                                                         '  MachinePromoBalance = ' +
                                                         ISNULL(CAST(@MachinePromoBal AS VarChar), '<null>') +
                                                         '  ServerPromoBalance = ' +
                                                         ISNULL(CAST(@SystemPromoBal AS VarChar), '<null>')

                                          EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
                                       END

                                    -- Reset @SystemPromoBal
                                    SET @SystemPromoBal = @MachPromoBalPrePlay

                                    -- If tpAdjustMachinePromoBalance returns 3 or 4 
                                    -- (Can't update promo balance or tpInsertCasinoTrans failed)
                                    -- set error 132
                                    IF (@ReturnCode IN (3,4))
                                       SET @ErrorID = 132 
                                 END
                              ELSE
                                 BEGIN
                                    -- Promo balance adjustment exceeds max balance adjustment.
                                    SET @ErrorID = 132

                                    -- If debugging, save promo balance values...
                                    IF (@Debug = 1)
                                       BEGIN
                                          SET @MsgText =
                                             'tpTransL Promo Balance difference exceeds adjustment threshold: ' +
                                             '  MachinePromoBal: '   + ISNULL(CAST(@MachinePromoBal AS VarChar), '<null>') +
                                             '  SysPromoBalance: '   + ISNULL(CAST(@SystemPromoBal AS VarChar), '<null>') +
                                             '  MaxBalAdjust: ' + ISNULL(CAST(@MaxBalAdjust AS VarChar), '<null>')

                                          EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
                                       END
                                 END
                           END
                        
                        -- First, calc what the new balance and promo balance should be.
                        IF (@SystemPromoBal = 0)
                           BEGIN
                              -- No promo balance.
                              SET @NewBalance = @Balance - @TabCost
                              SET @PromoAmountPlayed = 0
                           END
                        ELSE IF (@SystemPromoBal >= @TabCost)
                           -- All of the cost of play comes from the PromoBalance
                           -- and the system balance does not change.
                           BEGIN
                              SET @PromoAmountPlayed = @TabCost
                              SET @SystemPromoBal = @SystemPromoBal - @PromoAmountPlayed
                              SET @NewBalance = @Balance
                           END
                        ELSE
                           -- The Promotional Balance is less than the cost of play so we need to
                           -- reduce the system balance by the tab cost - the promo amount
                           -- and reset the promo balance to zero.
                           BEGIN
                              SET @PromoAmountPlayed = @SystemPromoBal
                              SET @NewBalance = @Balance - (@TabCost - @SystemPromoBal)
                              SET @SystemPromoBal = 0
                           END
                        
                        -- Is a player card required?
                        IF (@CardRequired = 1)
                           BEGIN
                              -- Yes, so update balance on CARD_ACCT.
                              UPDATE CARD_ACCT SET
                                 PROMO_AMOUNT = PROMO_AMOUNT + @PromoAmount,
                                 BALANCE      = @NewBalance
                              WHERE CARD_ACCT_NO = @CardAccount
                              
                              -- Now update promo balance on MACH_SETUP.

                              UPDATE MACH_SETUP SET PROMO_BALANCE = @SystemPromoBal
                              WHERE MACH_NO = @MachineNumber
                           END
                        ELSE
                           BEGIN
                              -- Cardless Play, set the new balance and promo balance on MACH_SETUP.
                              UPDATE MACH_SETUP SET
                                 BALANCE       = @NewBalance,
                                 PROMO_BALANCE = @SystemPromoBal
                              WHERE MACH_NO = @MachineNumber
                           END
                        
                        -- Test that the Balance is still positive.
                        IF (@NewBalance < 0)
                              SET @ErrorID = 118
                        
                        -- Is this a progressive game?
                        IF (@IsProgressive = 1)
                           BEGIN
                              -- Yes, so calculate the progressive contribution.
                              SET @ProgContribution = @TabCost * (@PRateCombined / 100)
                              
                              EXEC UpdateProgressivePools @ProgressiveTypeID, @AcctDate, @GameTypeCode, @MachineDenomination, @TabCost
                              
                              -- Debug mode?
                              IF (@Debug = 1)
                                 -- Yes, so log progressive information...
                                 BEGIN
                                    SET @MsgText =
                                       'tpTransL - ProgressiveTypeID: '
                                                              + ISNULL(CAST(@ProgressiveTypeID AS VarChar), '<null>') +
                                       '  ProgRate1: '        + ISNULL(CAST(@PRate1 AS VarChar), '<null>') +
                                       '  ProgRate2: '        + ISNULL(CAST(@PRate2 AS VarChar), '<null>') +
                                       '  ProgRate3: '        + ISNULL(CAST(@PRate3 AS VarChar), '<null>') +
                                       '  ProgContribution: ' + ISNULL(CAST(@ProgContribution AS VarChar), '<null>')
                                    
                                    EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
                                 END
                           END
                        
                        -- Validate the denomination.
                        IF EXISTS (
                              SELECT DENOM_VALUE
                              FROM DENOM_TO_GAME_TYPE
                                 INNER JOIN BANK ON DENOM_TO_GAME_TYPE.GAME_TYPE_CODE = BANK.GAME_TYPE_CODE
                                 INNER JOIN MACH_SETUP ON BANK.BANK_NO = MACH_SETUP.BANK_NO
                              WHERE MACH_NO = @MachineNumber AND DENOM_VALUE = @MachineDenom)
                           BEGIN
                              IF (@NewBalance <> @MachineBal)
                                 -- Balance is off.
                                 BEGIN
                                    -- If in Cardless Play mode set error to 105, otherwise to 120.
                                    -- 120 locks machine, 105 does not.
                                    IF (@CardRequired = 0)
                                       SET @ErrorID = 105
                                    ELSE
                                       SET @ErrorID = 120
                                    -- In either case, error text is the same...
                                    SET @ErrorText = ',Machine balance should be: ' +
                                       CONVERT(VarChar(16), @Balance) +
                                       ', balance submitted was: ' + CONVERT(VarChar(16), @MachineBal)
                                 END
                           END
                        ELSE
                           -- Denoms do not match.
                           BEGIN
                              SET @ErrorID = 107
                              SET @ErrorText = ',Denomination submitted:' + CONVERT(VarChar(16), @MachineDenom)
                              SET @ErrorText = @ErrorText + ' is not valid.'
                           END
                     END
                  ELSE
                     -- Deal is not active.
                     SET @ErrorID = 112
               END
            ELSE
               BEGIN
                  IF (@SequenceNum = @MachineSequence) And (@LastBalance = @MachineBalance)
                     BEGIN
                        -- Send the Last Error
                        SET @ErrorID = @ErrorNum
                        SET @SaveTrans = 0
                     END
                  ELSE                              
                     BEGIN
                        -- Duplicate Ticket only if not bingo.
                        SET @ErrorID = 119
                        SET @SaveTrans = 1                       
                     END
               END
         END
      ELSE
         -- Deal does not exist.
         SET @ErrorID = 111
   END

-- If no errors yet, check the Machine vs. System promotional balances...
IF (@ErrorID = 0 AND @SystemPromoBal <> @MachinePromoBal)
   BEGIN
      SET @ErrorID = 132
      SET @ErrorText = ', Machine promo balance is: ' + CONVERT(VarChar(16), @MachinePromoBal) +
                       ', System promo balance is: '  + CONVERT(VarChar(16), @SystemPromoBal)
   END

-- Handle any errors
IF (@ErrorID <> 0)
   BEGIN
      SELECT
         @ErrorDescription = ISNULL([DESCRIPTION], 'Undefined Error ' + CAST(@ErrorID AS VarChar(10))),
         @LockupMachine    = ISNULL(LOCKUP_MACHINE, 1),
         @ErrorTypeID      = ERROR_TYPE_ID
      FROM ERROR_LOOKUP
      WHERE ERROR_NO = @ErrorID
      
      -- If error is 132 then there was a promo balance mismatch that could not be adjusted
      -- so we will force the machine to lockup.
      IF (@ErrorID = 132)
         SET @LockupMachine = 1
      
      -- If in Cardless Play mode, reset error text.
      IF (@CardRequired = 0)

         SET @ErrorDescription = dbo.CardlessErrorText(@ErrorDescription)
      
      -- Build Error Message
      SET @EventLogDesc = 'Description: ' + @ErrorDescription +
                          ', Card Account: ' + @CardAccount +
                          ', Machine Number: ' + @MachineNumber +
                          ', Casino Machine Number: ' + ISNULL(@CasinoMachNo, '<null>')
      
      IF (LEN(@ErrorText) > 0)
         SET @EventLogDesc = @EventLogDesc + @ErrorText
      
      -- Test if the Machine should be loocked up.
      IF (@LockupMachine <> 0)
         BEGIN
            UPDATE MACH_SETUP SET ACTIVE_FLAG = 0 WHERE MACH_NO = @MachineNumber AND ACTIVE_FLAG = 1
            SET @EventCode = 'SD'
         END
      
      -- Insert Error into the Casino_Event_Log
      INSERT INTO CASINO_EVENT_LOG
         (EVENT_CODE, EVENT_SOURCE, EVENT_DESC, ERROR_NO, MACH_NO)
      VALUES
         (@EventCode, @ErrorSource, @EventLogDesc, @ErrorID, @MachineNumber)
      
      -- Update Machine_Last_Play
      UPDATE MACH_LAST_PLAY SET ERROR_NO = @ErrorID WHERE MACH_NO = @MachineNumber
      
      -- If the error is a tab error and playing a paper game,
      -- record the the tab error in the TAB_ERROR table.
      IF (@ErrorTypeID = 1 AND @IsPaper = 1)
         BEGIN
            INSERT INTO TAB_ERROR
               (MACH_NO, ERROR_NO, EVENT_TIME, LOCATION_ID, TICKET_NO)
            VALUES
               (@MachineNumber, @ErrorID, @TimeStamp, @LocationID, @TicketNumber)
         END
   END

IF (@SaveTrans >= 2)
   BEGIN
      -- Increment Deal Statistics counters
      UPDATE DEAL_STATS SET
         AMOUNT_PLAYED     = AMOUNT_PLAYED     + @TabCost,
         LOSS_COUNT        = LOSS_COUNT        + 1,
         PLAY_COUNT        = PLAY_COUNT        + 1,
         PROG_CONTRIBUTION = PROG_CONTRIBUTION + @ProgContribution,
         LAST_PLAY         = @TimeStamp
      WHERE DEAL_NO = @DealNo
      
      -- If no rows were modified, the record doesn't exist - so create it.
      IF (@@ROWCOUNT = 0)
         BEGIN
            INSERT INTO DEAL_STATS
               (DEAL_NO, AMOUNT_PLAYED, LOSS_COUNT, PLAY_COUNT, PROG_CONTRIBUTION, LAST_PLAY, FIRST_PLAY)
            VALUES
               (@DealNo, @TabCost, 1, 1, @ProgContribution, @TimeStamp, @TimeStamp)
         END
      
  DECLARE @MachineDenomCast smallmoney, @CoinsBetCast smallint, @LinesBetCast smallint
  SET @MachineDenomCast = CAST(@MachineDenom AS SmallMoney)
  SET @CoinsBetCast = CAST(@CoinsBet AS SmallInt)
  SET @LinesBetCast = CAST(@LinesBet AS SmallInt)
      
  EXEC tpUpdatePlayStatsHourlyAndDaily 
  @LocationIdPass = @LocationID,
@TimeStampPass = @TimeStamp,
@DenomPass = @MachineDenomCast,
@CoinsBetPass = @CoinsBetCast,
@LinesBetPass = @LinesBetCast,
@MachNoPass = @MachineNumber,
@CasinoMachNoPass = @CasinoMachNo,
@AcctDatePass = @AcctDate,
@DealNoPass = @DealNumber,
@GameCodePass = @MachGameCode,
@PlayCountPass = 1,
@AmountPlayedPass = @TabCost,
@AmountPlayedPromoPass = @PromoAmountPlayed,
@LossCountPass = 1,
@AmountLostPass = @TabCost,
@ProgContributionPass = @ProgContribution

      
      -- Update MACHINE_PLAY_STATS table...
      IF (@SummarizePlay = 1)
         EXEC tpUpdateMachinePlayStats
            @MachineNumber     = @MachineNumber,
            @CasinoMachineNbr  = @CasinoMachNo,
            @DealNo            = @DealNumber,
            @GameCode          = @MachGameCode,
            @Denom             = @MachineDenom,
            @CoinsBet          = @TotalCoinsBet,
            @LinesBet          = @LinesBet,
            @AmountPlayed      = @TabCost,
            @AmountWon         = @TransAmt,
            @AcctDate          = @AcctDate,
            @LocationID        = @LocationID
      
      -- Update MACHINE_METER table...
      UPDATE MACHINE_METER SET
         PLAY_COUNT        = PLAY_COUNT        + 1,
         AMOUNT_PLAYED     = AMOUNT_PLAYED     + @TabCost,
         PROG_CONTRIBUTION = PROG_CONTRIBUTION + @ProgContribution
      WHERE
         MACH_NO = @MachineNumber
      
      -- If no row was modified, the record doesn't exist - so create it.
      IF (@@ROWCOUNT = 0)
         BEGIN
            INSERT INTO MACHINE_METER
               (MACH_NO, AMOUNT_PLAYED, PLAY_COUNT, PROG_CONTRIBUTION)
            VALUES
               (@MachineNumber, @TabCost, 1, @ProgContribution)
         END
   END

IF (@SaveTrans >= 1)
   BEGIN
      -- Set the CASINO_TRANS balance value.
      SET @Balance = @NewBalance + @SystemPromoBal
      
      -- Log transaction.
      EXEC @CasinoTransID = tpInsertCasinoTrans
         @CasinoID, @DealNo, @RollNo, @TicketNo, @MachineDenom, @TransAmt,
         @Barcode, @TransID, @AcctDate, @TimeStamp, @MachineNumber,
         @CardAccount, @Balance, @MachGameCode, @CoinsBet, @LinesBet,
         @TierLevel, @PressUpCount, @LocationID, @MachineTimeStamp
   END

-- Did we get a balance error in Cardless Play mode?
IF (@ErrorID = 105)
   BEGIN
      -- Is the difference <= adjustment threshold?
      IF ((@MachineBal - @Balance) <= @MaxBalAdjust)
         BEGIN
            -- Yes, so we need to adjust the machine balance...
            EXEC tpAdjustMachineBalance
               @MachineNumber, @CardRequired, @MachineBal, @NewBalance, 'tpTransL',
               @MachineTimeStamp, @CasinoID, @AcctDate, @MachGameCode, @LocationID
         END
      ELSE
         -- The difference exceeds the max adjustment value, force a lockup.
         BEGIN
            SET @LockupMachine = 1
            
            -- If debugging, save balance values...
            IF (@Debug = 1)
               BEGIN
                  SET @MsgText =
                     'tpTransL Balance difference exceeds adjustment threshold: ' +
                     '  MachineBal: '   + ISNULL(CAST(@MachineBal AS VarChar), '<null>') +
                     '  SysBalance: '   + ISNULL(CAST(@NewBalance AS VarChar), '<null>') +
                     '  MaxBalAdjust: ' + ISNULL(CAST(@MaxBalAdjust AS VarChar), '<null>')
                  
                  EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
               END
         END
   END

-- If debugging, save return values...
IF (@Debug = 1)
   BEGIN
      SET @MsgText =
         'tpTransL Return Values - ErrorID: ' + CAST(@ErrorID AS VarChar(10)) +
         '  ErrorDescription: ' + @ErrorDescription +
         '  LockupMachine: ' + CAST(@LockupMachine AS VarChar(10))
      
      EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
   END

-- Return results to client
SELECT
   @ErrorID          AS ErrorID,
   @ErrorDescription AS ErrorDescription,
   @LockupMachine    AS ShutDownFlag
GO
