SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/*
--------------------------------------------------------------------------------
User Stored Procedure tpTransJ

Created 04-11-2003 by Chris Coddington

Desc: Handles all jackpot transactions.

Return values: ErrorCode, ErrorDescription, ShutdownFlag

Called by: Transaction Portal

Parameters:
   @Barcode             Barcode of the Ticket
   @CardAccount         Card Account number in use at the machine
   @CoinsBet            Number of Coins that were bet
   @CoinsWon            Number of Coins that were won
   @DealNumber          The Deal Number for this play
   @LinesBet            Number of Coins that were bet on
   @MachineBalance      What the machine sent as it's new balance
   @MachineDenomination Denomination played at the machine
   @MachineNumber       The Machine Number where play occurred
   @MachineSequence     A sequence number generated by the TransPortal
   @RollNo              The Roll Number of the ticket within the Deal
   @TicketNumber        The Ticket Number played
   @TierLevel           Tier Level of the win
   @TimeStamp           DateTime value sent from the Machine
   @PressUpCount        Number of times player pressed up their bet
                        (for the Press It Up Poker game)
   @PromoBalance        Promotional Balance in cents (default = 0)
   @ProgressiveAmount   Progressive Win Amount in cents (default = 0)

Press It Up Poker Note:
  The @CoinsBet value will contain the original number of coins bet regardless
  of whether the player 'Pressed Up' their bet.
  The @CoinsWon value will be the total number of coins won factoring in any
  player 'Press Ups'.


Change Log:

Changed By    Date           Database Version
  Change Description
--------------------------------------------------------------------------------
Terry Watkins 10-18-2003
  Change insert/update of DEAL_STATS and DAILY_DEAL_STATS to use @BaseTrans
  instead of @NetTrans. Also changed insert/update from Win_Count to Jackpot_Count
  on the DEAL_STATS and DAILY_DEAL_STATS.

Chris         12-15-2003
  Move Deal_Stats and Daily_Deal_Stats logic out of the error checking area.

Chris C.      02-10-2004
  Changed Float datatypes to Money datatypes.

Terry Watkins 02-23-2004
  Added code to update new MACHINE_STATS table.
  Added insertion of the Machine's Game Code into CASINO_TRANS.

Terry Watkins 04-20-2004
  Added code to handle Dakota Paper games. When calculating the number of coins
  won for a Payscale Tier when playing paper, use the number of coins bet as
  the Payscale Multiplier instead of using CASINO_FORMS.PAYSCALE_MULTIPLIER.

Chris C.      04-22-2004
  Changed duplicate ticket test to send back the last ack when sequence number
  and balance are the same.

Chris C.      05-05-2004
  Modified tpInsertCasinoTrans to accept denom.

Terry Watkins 07-07-2004
  Added insertion of a row into new Jackpot table.

Terry Watkins 07-07-2004
  Changed datatype of variable @LockupAmount from Int to SmallMoney.

  Added insertion of a row into new Jackpot table.

  Changed evaluation of Lockup from:
    IF @NetTrans > @LockupAmount
                 to
    IF @BaseTrans >= @LockupAmount

  Changed datatype of @MachineDenom from SmallMoney to Money to fix arithmetic
  overflow bug when calculating @BaseTrans and @TabCost with large @CoinsWon
  values.

Terry Watkins 07-20-2004
  Added update or insertion into new MICS_STATS table for electronic
  (fixed denom) games.

Terry Watkins 11-02-2004     v3.6.5
  Added update of new CARD_ACCT.PROMO_AMOUNT column.

Terry Watkins 11-04-2004     v4.0.0
  Added insertion of TransID into CASINO_TRANS and JACKPOT tables.
  Added support for cardless play.

Terry Watkins 01-13-2005     v4.0.1
  Added code to update new MACHINE_METER table.
  Added argument @PressUpCount to support new Press It Up Poker game.
  Added retrieval of @MultiBetDeals which is used to determine if the MICS_STATS
  table should be updated.
  Changed logic for update vs. insert into DAILY_DEAL_STATS to use EXISTS
  instead of looking at @@ROWCOUNT

A. Murthy     01-26-2005     v4.0.1
  For TITO set @CardAccount = 'INTERNAL'.

Terry Watkins 03-31-2005     v4.0.2
  Moved deactivation of eDeal ticket from tpTransT to tpTransL,W,J,and F.

Terry Watkins 05-10-2005     v4.1.1
  Added promotional coupon (eCoupon) handling:
    - Added argument @PromoBalance
    - Added logic to exhaust promotional balance before reducing machine or
      card account balance.

Terry Watkins 06-20-2005     v4.1.4
  Changed size of @CardAccount from 16 to 20.
  Added support for Keno - Balance checking and Payscale validation.

Terry Watkins 06-20-2005     v4.1.9
  Moved setting of @PromoAmount below where @TabCost is set.

Terry Watkins 09-07-2005     v5.0.0
  Changed the value inserted into CASINO_TRANS.BALANCE to be the total of the
  account balance plus the promo balance.

Terry Watkins 01-18-2006     v5.0.1
  Added retrieval of GameClass which is passed to tpDeactivateTicket so the
  ticket in the proper database (eDeal or eTab) is deactivated.

  Modified update to MACH_SETUP.ACTIVE_FLAG so that on error, the flag is set
  to 0 only if it is currently set to 1 (data type changed from Bit to TinyInt).

  Added ISNULL check to update of BANK.PROG_AMT for progressive deals.

Terry Watkins 01-18-2006     v5.0.2
  Added parameter @ProgressiveAmount which is the amount in cents that the
  machine is reporting as a Progressive Win amount.

  Added logic to update or insert a row into DEAL_INVENTORY if playing from a
  Paper Deal.
  
  Added retrieval of TierWinType from PAYSCALE_TIER or PAYSCALE_TIER_KENO to
  determine if the win is a true Jackpot or not.  The machine game code will
  send a J transaction whenever the win amount is greater than the lockup amount
  but progresive wins should only occur for true jackpots.

  Added logic to store the base transaction plus progressive pool amount won in
  CASINO_TRANS.TRANS_AMT for progressive wins and modified the progressive pool
  contribution to be the Tab Cost * Progressive % (was Mach Denom * Prog %).

  Removed code that updated DAILY_DEAL_STATS.  That table is no longer used.

  Added logic to NOT set CARD_ACCT.STATUS = 2 for an MGAM Jackpot (TPI_ID=2).

Terry Watkins 01-18-2006     v5.0.5
  Added logic to replace the Roll number sent from the machine with a calculated
  Roll number if playing from a Paper Deal.
  Cast @Balance to Int in returned resultset (fomatting issue in the log file)

Terry Watkins 10-04-2006     v5.0.8
  Added code to update new MACHINE_PLAY_STATS table.

  Removed @TicketStatusID. No longer needed because column
  CASINO_TRANS.TICKET_STATUS_ID has been removed.

A. Murthy     07-25-2007     v6.0.1
  For Bingo set @FormMultiplier = @CoinsBet and do not call tpDeactivateTicket.

A. Murthy     12-19-2007     v6.0.2
  Move retrieval of LOCKUP_AMOUNT from CASINO table to BANK table.

Terry Watkins 01-24-2008     v6.0.2
  Changed the datatype of @ProgressivePct from Int to Decimal(6,4).

Terry Watkins 01-24-2008     v6.0.5
  The summary tables will no longer be updated when an invalid tier error (113)
  is encountered, however, an entry will still be made in CASINO_TRANS.

Terry Watkins 07-22-2008     v7.0.0
  Added Progressive support.
  
  Uses new function dbo.ufnGetAcctDate() to retrieve the accounting date.
  
  @AcctDate changed from VarChar(16) to DateTime.
  
  Added code to disallow balance adjustments that exceed the value set in
  CASINO.MAX_BAL_ADJUSTMENT.

Terry Watkins 07-22-2008     v7.1.0
  Added EXEC of new sp tpUpdatePoolContribution which records progressive pool
  contributions by accounting date to each pool.

Terry Watkins 05-12-2010     v7.2.1
  Modified insert into CASINO_EVENT_LOG to update new columns ERROR_NO and
  MACH_NO.
  
Terry Watkins 08-10-2010     v7.2.3
  Modified to no longer update PROGRESSIVE_POOL AND to no longer EXECUTE
  tpUpdatePoolContribution if the jackpot is a progressive win. Those updates
  will have already happened in tpTransP which is executed when a machine
  claims the progressive prize.

Terry Watkins 10-14-2010     v7.2.4
  Added the recording of tab errors in the TAB_ERROR table if playing a paper
  game.

Terry Watkins 11-10-2010     DCLRetail v1.0.0
  Added retrieval of Location ID from the CASINO table for insertion into
  CASINO_TRANS.LOCATION_ID and JACKPOT.LOCATION_ID.
  Added insertion into (or updating of) table PLAY_STATS_HOURLY.

Aldo Zamora 04-22-2013     Lottery Retail v3.1.0
  Added LocationID WHEN updating the TabError table.
  
Louis Epstein 10-25-2013     v3.1.6
  Added machine timestamp functionality
  
Louis Epstein 12-23-2013     v3.1.7
  Added promo credits functionality
  
Eloy Bencomo 03-04-2014      v3.1.8
  Added TicketNumber Logging to TAB_ERROR
  
Louis Epstein 04-10-2014     v3.2.1
  Added functionality to contribute to multi level progressive pools
  
Louis Epstein 06-18-2014     v3.2.3
  Modified stat recording functionality to use tpUpdatePlayStatsHourlyAndDaily
----------------------------------------------------------------------------------
*/
CREATE PROCEDURE [dbo].[tpTransJ]
   @Barcode             VarChar(128),
   @CardAccount         VarChar(20),
   @CoinsBet            Int,
   @CoinsWon            Int,
   @DealNumber          Int,
   @LinesBet            Int,
   @MachineBalance      Int,
   @MachineDenomination Int,
   @MachineNumber       VarChar(5),
   @MachineSequence     Int,
   @RollNo              Int,
   @TicketNumber        Int,
   @TierLevel           SmallInt,
   @TimeStamp           DateTime,
   @PressUpCount        SmallInt,
   @PromoBalance        Int = 0,
   @ProgressiveAmount   Int = 0
AS

-- Variable Declarations
DECLARE @AcctDate           DateTime
DECLARE @BaseBalance        Money
DECLARE @Balance            Money
DECLARE @BaseTrans          Money
DECLARE @BankNumber         Int
DECLARE @CardRequired       Bit
DECLARE @CasinoID           VarChar(6)
DECLARE @CasinoMachNo       VarChar(8)
DECLARE @CasinoTransID      Int
DECLARE @CTBalance          Money
DECLARE @CTTransAmount      Money
DECLARE @DealNo             Int
DECLARE @DealTypeCode       Char(1)
DECLARE @Debug              Bit
DECLARE @ErrorDescription   VarChar(256)
DECLARE @ErrorID            Int
DECLARE @ErrorNum           Int
DECLARE @ErrorOverride      Int
DECLARE @ErrorSource        VarChar(64)
DECLARE @ErrorText          VarChar(1024)
DECLARE @ErrorTypeID        Int
DECLARE @EventCode          VarChar(2)
DECLARE @EventLogDesc       VarChar(1024)
DECLARE @FormMultiplier     Int
DECLARE @FormNumber         VarChar(10)
DECLARE @GameClass          SmallInt
DECLARE @GameTypeCode       VarChar(2)
DECLARE @HourOfDay          Int
DECLARE @IntValue           Int
DECLARE @IsActive           Bit
DECLARE @IsBingo            Bit
DECLARE @IsPaper            Bit
DECLARE @IsProgressiveGame  Bit
DECLARE @IsProgressiveWin   Bit
DECLARE @IsPromoOn          Bit
DECLARE @LastBalance        Int
DECLARE @LocationID         Int
DECLARE @LockupAmount       SmallMoney
DECLARE @LockupCard         Bit
DECLARE @LockupMachine      Int
DECLARE @MachNbrAsInt       Int
DECLARE @MachGameCode       Char(3)
DECLARE @MachineBal         Money
DECLARE @MachineDenom       Money
DECLARE @MachinePromoBal    Money
DECLARE @MachNo             VarChar(5)
DECLARE @MaxBalAdjust       Money
DECLARE @MsgText            VarChar(2048)
DECLARE @MultiBetDeals      Bit
DECLARE @NetTrans           Money
DECLARE @NewSystemPromoBal  Money
DECLARE @PayscaleName       VarChar(16)
DECLARE @PlayStatsHourlyID  Int
DECLARE @PRate1             Decimal(9,8)
DECLARE @PRate2             Decimal(9,8)
DECLARE @PRate3             Decimal(9,8)
DECLARE @PRateCombined      Decimal(9,8)
DECLARE @ProductLineID      SmallInt
DECLARE @ProgAwardFactor    Int
DECLARE @ProgContribution   Money
DECLARE @ProgressiveAmt     Money
DECLARE @ProgressiveTypeID  Int
DECLARE @PromoAmount        SmallMoney
DECLARE @PromoAmountPlayed     SmallMoney
DECLARE @PromoAmountWon     Money
DECLARE @SaveTrans          Int
DECLARE @SequenceNum        Int
DECLARE @SummarizePlay      Bit
DECLARE @SystemPromoBal     Money
DECLARE @TabCost            SmallMoney
DECLARE @TabsPerSubset      Int
DECLARE @TicketNo           Int
DECLARE @TierCoinsWon       Int
DECLARE @TierUseMultiplier  Int
DECLARE @TierWinType        SmallInt
DECLARE @TotalCoinsBet      Int
DECLARE @TpiID              Int
DECLARE @TransID            SmallInt
DECLARE @MachineTimeStamp   DateTime

SET NOCOUNT ON

-- Variable Initialization
SET @MachineTimeStamp = @TimeStamp
SET @BaseBalance        = 0
SET @Balance            = 0
SET @CardRequired       = 1
SET @CasinoTransID      = 0
SET @CTBalance          = 0
SET @CTTransAmount      = 0
SET @DealNo             = @DealNumber
SET @DealTypeCode       = ' '
SET @ErrorDescription   = ''
SET @ErrorID            = 0
SET @ErrorOverride      = 0
SET @ErrorSource        = 'tpTransJ Stored Procedure'
SET @ErrorText          = ''
SET @ErrorTypeID        = 0
SET @EventCode          = 'SP'
SET @FormMultiplier     = 0
SET @FormNumber         = ''
SET @GameClass          = 2
SET @GameTypeCode       = ''
SET @EventLogDesc       = ''
SET @IsActive           = 0
SET @IsBingo            = 0
SET @IsPaper            = 0
SET @IsProgressiveGame  = 0
SET @IsProgressiveWin   = 0
SET @IsPromoOn          = 0
SET @LocationID         = 0
SET @LockupAmount       = 0
SET @LockupCard         = 0
SET @LockupMachine      = 0
SET @MachNbrAsInt       = CAST(@MachineNumber AS Int)
SET @MsgText            = ''
SET @MultiBetDeals      = 0
SET @NewSystemPromoBal  = 0
SET @PRate1             = 0
SET @PRate2             = 0
SET @PRate3             = 0
SET @PRateCombined      = 0
SET @ProductLineID      = 0
SET @ProgContribution   = 0
SET @ProgressiveTypeID  = 0
SET @PromoAmount        = 0
SET @PromoAmountPlayed     = 0
SET @PromoAmountWon     = 0
SET @SaveTrans          = 2
SET @SystemPromoBal     = 0
SET @TabsPerSubset      = 0
SET @TicketNo           = @TicketNumber
SET @TierCoinsWon       = 0
SET @TierUseMultiplier  = 0
SET @TierWinType        = 0
SET @TotalCoinsBet      = @CoinsBet
SET @TransID            = 12
SET @TimeStamp          = GetDate()

-- Convert balance and denom before calculating transaction amounts...
SET @MachineBal         = CAST(@MachineBalance AS MONEY) / 100
SET @MachineDenom       = CAST(@MachineDenomination AS MONEY) / 100
SET @MachinePromoBal    = CAST(@PromoBalance AS MONEY) / 100
SET @ProgressiveAmt     = CAST(@ProgressiveAmount AS MONEY) / 100

-- If the progressive win amount > 0 then set the Progressive Win flag.
IF (@ProgressiveAmount > 0)
   SET @IsProgressiveWin = 1

-- Check Debug mode...
SELECT @Debug = ISNULL(DEBUG_MODE, 0) FROM DEBUG_SETTING WHERE DEBUG_ENTITY = 'tpTransJ'

-- If Debug mode, save argument values...
IF (@Debug = 1)
   -- Record argument values.
   BEGIN
      SET @MsgText =
         'tpTransJ Argument Values:  ' + 
         '  Barcode: '             + ISNULL(@Barcode, '<null>') +
         '  CardAccount: '         + ISNULL(@CardAccount, '<null>') +
         '  CoinsBet: '            + ISNULL(CAST(@CoinsBet AS VarChar), '<null>') +
         '  CoinsWon: '            + ISNULL(CAST(@CoinsWon AS VarChar), '<null>') +
         '  DealNumber: '          + ISNULL(CAST(@DealNumber AS VarChar), '<null>') +
         '  LinesBet: '            + ISNULL(CAST(@LinesBet AS VarChar), '<null>') +
         '  MachineBalance: '      + ISNULL(CAST(@MachineBalance AS VarChar), '<null>') +
         '  MachineDenomination: ' + ISNULL(CAST(@MachineDenomination AS VarChar), '<null>') +
         '  MachineNumber: '       + ISNULL(@MachineNumber, '<null>') +
         '  MachineSequence: '     + ISNULL(CAST(@MachineSequence AS VarChar), '<null>') +
         '  RollNo: '              + ISNULL(CAST(@RollNo AS VarChar), '<null>') +
         '  TicketNumber: '        + ISNULL(CAST(@TicketNumber AS VarChar), '<null>') +
         '  TierLevel: '           + ISNULL(CAST(@TierLevel AS VarChar), '<null>') +
         '  PressUpCount: '        + ISNULL(CAST(@PressUpCount AS VarChar), '<null>') +
         '  PromoBalance: '        + ISNULL(CAST(@PromoBalance AS VarChar), '<null>') +
         '  ProgressiveAmount: '   + ISNULL(CAST(@ProgressiveAmount AS VarChar), '<null>')
      
      EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
   END

-- Retrieve CASINO information.
SELECT
   @CasinoID      = CAS_ID,
   @CardRequired  = PLAYER_CARD,
   @IsPromoOn     = PROMOTIONAL_PLAY,
   @TpiID         = TPI_ID,
   @SummarizePlay = SUMMARIZE_PLAY,
   @MaxBalAdjust  = MAX_BAL_ADJUSTMENT,
   @LocationID    = LOCATION_ID
FROM CASINO
WHERE SETASDEFAULT = 1

-- If @CardRequired is 0 (TITO), set @CardAccount to 'INTERNAL'
IF (@CardRequired = 0)
   SET @CardAccount = 'INTERNAL'

-- Get Current Accounting Date and hour of the day...
SET @AcctDate  = dbo.ufnGetAcctDate()
SET @HourOfDay = dbo.ufnCurrentHour()

-- Check for existance, active, removed status of machine.
SET @ErrorID = dbo.GetMachineStatus(@MachineNumber)

-- If the MACH_SETUP row was found, retrieve Machine information.
IF (@ErrorID <> 104)
   BEGIN
      SELECT
         @CasinoMachNo      = ms.CASINO_MACH_NO,
         @MachGameCode      = ms.GAME_CODE,
         @IsActive          = ms.ACTIVE_FLAG,
         @BankNumber        = ms.BANK_NO,
         @Balance           = ms.BALANCE,
         @SystemPromoBal    = ms.PROMO_BALANCE,
         @GameTypeCode      = gt.GAME_TYPE_CODE,
         @DealTypeCode      = gt.TYPE_ID,
         @ProgressiveTypeID = gt.PROGRESSIVE_TYPE_ID,
         @GameClass         = pl.GAME_CLASS,
         @ProductLineID     = pl.PRODUCT_LINE_ID,
         @LockupAmount      = b.LOCKUP_AMOUNT
      FROM MACH_SETUP ms
         JOIN BANK          b ON ms.BANK_NO = b.BANK_NO
         JOIN PRODUCT_LINE pl ON b.PRODUCT_LINE_ID = pl.PRODUCT_LINE_ID
         JOIN GAME_TYPE    gt ON b.GAME_TYPE_CODE = gt.GAME_TYPE_CODE
      WHERE ms.MACH_NO = @MachineNumber
      
      -- Is this a progressive game?
      IF (@ProgressiveTypeID = 0)
         BEGIN
            -- No, not a progressive game, check for progressive win.
            IF (@IsProgressiveWin <> 0)
               -- Non-Progressive game should never send a progressive win amount.
               SET @ErrorID = 337
         END
      ELSE
         -- Yes it is a progressive game, so get progressive info...
         BEGIN
            -- Set the progressive flag.
            SET @IsProgressiveGame = 1
            
                  -- Does a row exist for the PROGRESSIVE_TYPE_ID of the Game Type?
                  IF EXISTS(SELECT * FROM PROGRESSIVE_TYPE WHERE PROGRESSIVE_TYPE_ID = @ProgressiveTypeID)
                     BEGIN
                        -- Yes, so retrieve ProgressiveType data...
                        SELECT
@PRateCombined = SUM(Rate1) + SUM(Rate2) + SUM(Rate3)
FROM PROGRESSIVE_POOL
WHERE PROGRESSIVE_TYPE_ID = @ProgressiveTypeID AND DENOMINATION = @MachineDenomination
GROUP BY PROGRESSIVE_TYPE_ID, DENOMINATION
                        
                        -- If debug mode, record Progressive Type info.
                        IF (@Debug = 1)
                           -- Record argument values.
                           BEGIN
                              SET @MsgText = 'tpTransJ Progressive Type Values: ProgressiveTypeID: ' +
                                 ISNULL(CAST(@ProgressiveTypeID AS VarChar), '<null>') +
                                 '  PRate1: ' + ISNULL(CAST(@PRate1 AS VarChar), '<null>') +
                                 '  PRate2: ' + ISNULL(CAST(@PRate2 AS VarChar), '<null>') +
                                 '  PRate3: ' + ISNULL(CAST(@PRate3 AS VarChar), '<null>') +
                                 '  PRateCombined: ' + ISNULL(CAST(@PRateCombined AS VarChar), '<null>')
                              
                              EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
                           END
                        
                        END
            ELSE
               BEGIN
                  -- PROGRESSIVE_TYPE row not found.
                  SET @ErrorID = 335
               END


            -- It may be a progessive game but is it also a progressive win?
            IF (@IsProgressiveWin = 1 AND @ErrorID = 0)
                     BEGIN                  

                              -- Yes, so retrieve PROG_AWARD_FACTOR data...
                              -- The Award Factor is the number of coins added to the progressive seed amount
                              -- from the top award so that the progressive pool amount displays properly.
                              SELECT @ProgAwardFactor = AWARD_FACTOR
                              FROM PROG_AWARD_FACTOR
                              WHERE
                                 PROGRESSIVE_TYPE_ID = @ProgressiveTypeID AND
                                 TIER_LEVEL = @TierLevel

                             IF @ProgAwardFactor IS NULL
                             BEGIN
SELECT @ProgAwardFactor = (COINS_WON * @CoinsBet)
FROM PAYSCALE_TIER

WHERE PAYSCALE_NAME LIKE 'PS' + @GameTypeCode + '%' AND TIER_LEVEL = @TierLevel
                             END

                             IF @ProgAwardFactor IS NULL
                             BEGIN
SELECT @ProgAwardFactor = COINS_WON
FROM WINNING_TIERS
WHERE FORM_NUMB = @FormNumber AND TIER_LEVEL = @TierLevel

                             END

                             IF @ProgAwardFactor IS NULL
                             BEGIN
-- PROG_AWARD_FACTOR row not found.
SET @ErrorID = 336
                             END
                             ELSE
                             BEGIN
                              -- If debug mode, record Award Factor info.
                              IF (@Debug = 1)
                                 -- Record argument values.
                                 BEGIN
                                    SET @MsgText = 'tpTransJ Progressive Award Factor Value: ' +
                                       ISNULL(CAST(@ProgAwardFactor AS VarChar), '<null>')

                                    EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
                                 END
                             END
                     END
         END
      
      -- Set Bingo Machine Flag
      IF (@ProductLineID = 7)
         SET @IsBingo = 1
      
      -- Deactive the ticket in the eDeal or eTab database.
      IF (@IsBingo = 0)
         EXEC tpDeactivateTicket @DealNumber, @TicketNumber, @GameClass
      
      -- Set transaction amounts...
      IF (@DealTypeCode <> 'K')
         -- Non-Keno game/machine.
         BEGIN
            -- Set Transaction amount variables, Non-Keno...
            SET @BaseTrans = @MachineDenom * @CoinsWon 
            SET @TabCost   = @MachineDenom * @CoinsBet * @LinesBet
            IF (@PressUpCount > 0)
               BEGIN
                  SET @TabCost = (@TabCost * (@PressUpCount + 1))
                  SET @TotalCoinsBet = (@TotalCoinsBet * (@PressUpCount + 1))
               END
         END
      ELSE
         -- Keno game/machine.
         BEGIN
            -- Set Transaction amount variables, Keno...
            SET @BaseTrans = CAST(@CoinsWon AS Money) / 100
            SET @TabCost   = @MachineDenom * @CoinsBet
         END
      
      -- Store Base transaction amount in @CTTransAmount (which will be inserted into CASINO_TRANS.TRANS_AMT)
      SET @CTTransAmount = @BaseTrans + @ProgressiveAmt
      
      -- Reset the Promotional Amount that will be added to CARD_ACCT.PROMO_AMOUNT if CASINO.PROMOTIONAL_PLAY is set.
      IF (@IsPromoOn = 1)
         SET @PromoAmount = @TabCost
      
      -- Do we have a positive system promotional balance?
      IF (@SystemPromoBal > 0)
         -- Yes
         BEGIN
            -- Calculate the new system promo balance...
            SET @NewSystemPromoBal = @SystemPromoBal - @TabCost
            IF (@NewSystemPromoBal < 0) SET @NewSystemPromoBal = 0
            
            -- Calculate and store the amount by which the system promo amount will be reduced.
            SET @PromoAmountPlayed = @SystemPromoBal - @NewSystemPromoBal

            -- Calculate the net transaction amount (the amount by which the system balance will be increased)
            IF (@PromoAmountPlayed < @TabCost)
               BEGIN
                  -- Promo amount did not cover the entire cost of play.
                  SET @NetTrans = @BaseTrans - (@TabCost - @PromoAmountPlayed)
                  -- Set the Promo amount won to a fractional amount based on the promo amount played.
                  SET @PromoAmountWon = ROUND(@CTTransAmount * (@PromoAmountPlayed / @TabCost), 2)
               END
            ELSE
               BEGIN
                  -- Promo amount was enough to cover the entire cost of play.
                  SET @NetTrans = @BaseTrans
                  SET @PromoAmountWon = @CTTransAmount
               END
         END
      ELSE
         -- No promo balance, so set net transaction amount to the win amount minus the cost of play.
         BEGIN
            SET @NetTrans = @BaseTrans - @TabCost
         END
   END

IF (@Debug = 1)
   BEGIN
      -- Record Calculated values.
      SET @MsgText = 'tpTransJ Calculated values:  BaseTrans: '
                                 + ISNULL(CAST(@BaseTrans AS VarChar), '<null>')         +
         '  TabCost: '           + ISNULL(CAST(@TabCost AS VarChar), '<null>')           +
         '  NetTrans: '          + ISNULL(CAST(@NetTrans AS VarChar), '<null>')          +
         '  SystemPromoBal: '    + ISNULL(CAST(@SystemPromoBal AS VarChar), '<null>')    +
         '  NewSystemPromoBal: ' + ISNULL(CAST(@NewSystemPromoBal AS VarChar), '<null>') +
         '  PromoAmountPlayed: ' + ISNULL(CAST(@PromoAmountPlayed AS VarChar), '<null>') +
         '  PromoAmountWon: '    + ISNULL(CAST(@PromoAmountWon AS VarChar), '<null>')    +
         '  ErrorID: '           + ISNULL(CAST(@ErrorID AS VarChar), '<null>')

      
      EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
   END

-- Check that the Machine Promo Balance equals the new system promo balance.
IF (@NewSystemPromoBal <> @MachinePromoBal)
   BEGIN
      IF ((@MachinePromoBal - @NewSystemPromoBal) <= @MaxBalAdjust)
         BEGIN
            -- Promotional Balance mismatch (changed 12-08-11 to adjust promo balance and not set error 132).
            -- SET @ErrorID = 132

            -- Adjust the server Promo amount (changed 12-08-11)
            EXEC tpAdjustMachinePromoBalance
               @MachineNumber, @CardRequired, @MachinePromoBal, @NewSystemPromoBal, 'tpTransJ',
               @TimeStamp, @CasinoID, @AcctDate, @MachGameCode, @LocationID

            IF (@Debug = 1)
               BEGIN
                  SET @MsgText = 'tpTransJ executed tpAdjustMachinePromoBalance: MachinePromoBalance = ' +
                                 ISNULL(CAST(@MachinePromoBal AS VarChar), '<null>') +
                                 '  ServerPromoBalance = ' +
                                 ISNULL(CAST(@NewSystemPromoBal AS VarChar), '<null>')

                  EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
               END

            -- Reset the new system Promo balance (it is used below).
            SET @NewSystemPromoBal = @MachinePromoBal
         END
      ELSE
         BEGIN
            -- Promo balance adjustment exceeds max balance adjustment.
            SET @ErrorOverride = 132
            SET @ErrorText = ', Promo Balance Adjustment exceeds Max adjustment value.'

            -- If debugging, save promo balance values...
            IF (@Debug = 1)
               BEGIN
                  SET @MsgText =
                     'tpTransJ Promo Balance difference exceeds adjustment threshold: ' +
                     '  MachinePromoBal: '    + ISNULL(CAST(@MachinePromoBal AS VarChar), '<null>') +
                     '  NewSysPromoBalance: ' + ISNULL(CAST(@NewSystemPromoBal AS VarChar), '<null>') +
                     '  MaxBalAdjust: '       + ISNULL(CAST(@MaxBalAdjust AS VarChar), '<null>')

                  EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
               END
         END
   END

-- Is a Card required for Game Play?
IF (@ErrorID = 0 AND @CardRequired = 1)
   BEGIN
      -- Yes, so retrieve Balance and Machine number from the CARD_ACCT table.
      -- Note that for cardless play, we already have the balance from line 252.
      SELECT
         @MachNo = MACH_NO,
         @Balance = BALANCE
      FROM CARD_ACCT
      WHERE CARD_ACCT_NO = @CardAccount
      
      -- Did we find the CARD_ACCT row?
      IF (@@ROWCOUNT = 0)
         -- Card does not exist.
         SET @ErrorID = 102
      ELSE IF (@MachNo <> @MachineNumber)
         -- Card Account machine number does not match incoming machine number.
         SET @ErrorID = 108
   END

-- Has an error been encountered?
IF (@ErrorID = 0)
   BEGIN
      -- No, so update MACH_SETUP.LAST_ACTIVITY...
      UPDATE MACH_SETUP SET LAST_ACTIVITY = @TimeStamp WHERE MACH_NO = @MachineNumber
      
      -- Retrieve Deal, GameType, and Payscale info.
      SELECT
         @IsActive       = ds.IS_OPEN,
         @FormNumber     = ds.FORM_NUMB,
         @IsPaper        = cf.IS_PAPER,
         @FormMultiplier = cf.PAYSCALE_MULTIPLIER,
         @PayscaleName   = ps.PAYSCALE_NAME,
         @MultiBetDeals  = gt.MULTI_BET_DEALS,
         @TabsPerSubset  = ds.TABS_PER_ROLL
      FROM DEAL_SETUP ds
         JOIN CASINO_FORMS cf ON ds.FORM_NUMB = cf.FORM_NUMB
         JOIN GAME_TYPE    gt ON cf.GAME_TYPE_CODE = gt.GAME_TYPE_CODE
         JOIN PAYSCALE     ps ON gt.GAME_TYPE_CODE = ps.GAME_TYPE_CODE
      WHERE DEAL_NO = @DealNo
      
      -- Does the Deal exist?
      IF (@@ROWCOUNT > 0)
         BEGIN
            -- Yes, if this is a Paper Deal, reset the Form (Payscale) Multiplier to 
            -- the number of coins bet and replace the Roll number with a calculated value.
            IF (@IsPaper = 1)
               BEGIN
                  SET @FormMultiplier = @CoinsBet
                  SET @RollNo = dbo.GetRollNumber(@TicketNumber, @TabsPerSubset)
               END

            -- Bingo Machine ?
            IF (@IsBingo = 1)
               SET @FormMultiplier = @CoinsBet
            
            DECLARE @DealNum Int
            DECLARE @RollNum Int
            DECLARE @TicketNum Int
            DECLARE @BarcodeScan VarChar(128)
            DECLARE @Coins Int
            DECLARE @Lines Int
            
            -- Place last play information into table.
            UPDATE MACH_LAST_PLAY SET
               @DealNum       = DEAL_NO,
               @RollNum       = ROLL_NO,
               @TicketNum     = TICKET_NO,
               @BarcodeScan   = BARCODE_SCAN,
               @Coins         = COINS_BET,
               @Lines         = LINES_BET,
               @SequenceNum   = SEQUENCE_NO,
               @LastBalance   = BALANCE,
               @ErrorNum      = ERROR_NO,
               DEAL_NO        = @DealNumber,
               ROLL_NO        = @RollNo,
               TICKET_NO      = @TicketNumber,
               BARCODE_SCAN   = @Barcode,
               COINS_BET      = @CoinsBet,
               LINES_BET      = @LinesBet,
               ERROR_NO       = 0,
               SEQUENCE_NO    = @MachineSequence,
               BALANCE        = @MachineBalance,
               DTIMESTAMP     = @TimeStamp
            WHERE MACH_NO     = @MachineNumber
            
            IF (@@ROWCOUNT = 0)
               -- Machine doesn't exist in table, so insert a record.
               BEGIN
                  INSERT INTO MACH_LAST_PLAY
                     (MACH_NO, DEAL_NO, ROLL_NO, TICKET_NO, BARCODE_SCAN, COINS_BET, LINES_BET, ERROR_NO, SEQUENCE_NO, BALANCE, DTIMESTAMP)
                  VALUES
                     (@MachineNumber, @DealNumber, @RollNo, @TicketNumber, @Barcode, @CoinsBet, @LinesBet, 0, @MachineSequence, @MachineBalance, @TimeStamp)
                  
                  SET @DealNum = 0
                  SET @TicketNum = 0
               END
            
            -- Is this play the same as the last play?
            IF NOT((@DealNum = @DealNumber) AND (@TicketNum = @TicketNumber))
               BEGIN
                  -- No it is not, so test that the deal is open.
                  IF (@IsActive = 1)
                     -- The Deal is open.
                     BEGIN
                     -- Update or Insert into DEAL_INVENTORY if playing a Paper Deal...
                     IF (@IsPaper = 1)
                        BEGIN
                           -- Attempt an update.
                           UPDATE DEAL_INVENTORY SET
                              PLAY_COUNT = PLAY_COUNT + 1,
                              LAST_PLAY = @TimeStamp
                           WHERE
                              DEAL_NO = @DealNumber    AND
                              ROLL_NO = @RollNo        AND
                              MACH_NO = @MachineNumber
                           -- Was a row updated?
                           IF (@@ROWCOUNT = 0)
                              INSERT INTO DEAL_INVENTORY
                                 (DEAL_NO, ROLL_NO, MACH_NO, PLAY_COUNT, FIRST_PLAY, LAST_PLAY)
                              VALUES
                                 (@DealNumber, @RollNo, @MachineNumber, 1, @TimeStamp, @TimeStamp)
                        END
                        
                        -- Validate the Tier
                        IF (@DealTypeCode <> 'K')
                           -- Non-Keno.
                           BEGIN
                              SELECT
                                 @TierCoinsWon      = COINS_WON, 
                                 @TierUseMultiplier = USE_MULTIPLIER,
                                 @TierWinType       = TIER_WIN_TYPE
                              FROM PAYSCALE_TIER
                              WHERE
                                 PAYSCALE_NAME = @PayscaleName AND
                                 TIER_LEVEL = @TierLevel
                              
                              -- If Use Multiplier flag is set, recalc coins won for the tier.
                              IF (@TierUseMultiplier = 1)
                                 SET @TierCoinsWon = @TierCoinsWon * @FormMultiplier
                              
                              -- Did player 'Press Up' their bet?
                              IF (@PressUpCount > 0) SET @TierCoinsWon = (@TierCoinsWon * (@PressUpCount + 1))
                           END
                        ELSE
                           -- Keno.
                           BEGIN
                              SELECT
                                 @TierCoinsWon      = CAST(@MachineDenomination * AWARD_FACTOR AS Integer) * @CoinsBet,
                                 @TierUseMultiplier = 0,
                                 @TierWinType       = TIER_WIN_TYPE
                              FROM PAYSCALE_TIER_KENO
                              WHERE
                                 PAYSCALE_NAME = @PayscaleName AND
                                 TIER_LEVEL = @TierLevel
                           END
                        
                        -- If in debug mode, save calced values...
                        IF (@Debug = 1)
                           BEGIN
                              SET @MsgText =
                                 'tpTransJ - TierCoinsWon: ' + CAST(@TierCoinsWon AS VarChar) +
                                 '  TierUseMultiplier: ' + CAST(@TierUseMultiplier AS VarChar) +
                                 '  FormMultiplier: ' + CAST(@FormMultiplier AS VarChar) +
                                 '  TierLevel: ' + CAST(@TierLevel AS VarChar)
                              
                              EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
                           END
                        
                        -- Test that the number of coins won agrees with tier info.
                        IF (@TierCoinsWon = (@CoinsWon + ISNULL(@ProgAwardFactor, 0)))
                           BEGIN
                              -- Is this a Progressive game with no errors?
                              IF (@IsProgressiveGame = 1 AND @ErrorID = 0)
                                 BEGIN
                                    -- Yes, so calculate the progressive contribution.
                                    SET @ProgContribution = @TabCost * (@PRateCombined / 100)
                                    
                                    -- Update the progressive pool values if this is not a progressive win
                                    -- (progressive wins cause pool updates in tpTransP)...
                                    IF (@IsProgressiveWin = 0)
                                       BEGIN
                                          EXEC UpdateProgressivePools @ProgressiveTypeID, @AcctDate, @GameTypeCode, @MachineDenomination, @TabCost
                                       END
                                    
                                    -- Debug mode?
                                    IF (@Debug = 1)
                                       -- Yes, so log progressive information...
                                       BEGIN
                                          SET @MsgText =
                                             'tpTransJ - ProgressiveTypeID: '
                                                                    + ISNULL(CAST(@ProgressiveTypeID AS VarChar), '<null>') +
                                             '  GameTypeCode: '     + ISNULL(@GameTypeCode, '<null>') +
                                             '  ProgRate1: '        + ISNULL(CAST(@PRate1 AS VarChar), '<null>') +
                                             '  ProgRate2: '        + ISNULL(CAST(@PRate2 AS VarChar), '<null>') +
                                             '  ProgRate3: '        + ISNULL(CAST(@PRate3 AS VarChar), '<null>') +
                                             '  ProgContribution: ' + ISNULL(CAST(@ProgContribution AS VarChar), '<null>') 
                                          
                                          EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
                                       END
                                 END
                              
                              -- Make balance change (per Norm - it is okay to adjust the balance without checking the denom first).
                              SET @BaseBalance = @Balance + @NetTrans
                              SET @Balance = @BaseBalance + ROUND(@ProgressiveAmt, 2)
                              
                              -- Make balance change and update promo amount.
                              -- (per Norm - it is okay to adjust the balance without checking the denom first).
                              IF (@CardRequired = 1)
                                 BEGIN
                                    -- Card Play, update the balance on CARD_ACCT.
                                    UPDATE CARD_ACCT SET
                                       PROMO_AMOUNT = PROMO_AMOUNT + @PromoAmount,
                                       BALANCE      = @Balance
                                    WHERE CARD_ACCT_NO = @CardAccount
                                    
                                    -- Update MACH_SETUP.PROMO_BALANCE if necessary.
                                    IF (@PromoAmountPlayed > 0)
                                       BEGIN
                                          UPDATE MACH_SETUP
                                          SET PROMO_BALANCE = @NewSystemPromoBal
                                          WHERE MACH_NO = @MachineNumber
                                       END
                                 END
                              ELSE
                                 BEGIN
                                    -- Cardless Play, update the balance on MACH_SETUP.
                                    UPDATE MACH_SETUP SET
                                       BALANCE = @Balance,
                                       PROMO_BALANCE = @NewSystemPromoBal
                                    WHERE MACH_NO = @MachineNumber
                                 END
                              
                              -- Is the Win Amount greater than the lockup amount?
                              IF (@CTTransAmount >= @LockupAmount)
                                 BEGIN
                                    -- Deactivate the card if in Card Required mode and NOT Mgam card.
                                    IF ((@CardRequired = 1) AND (@TpiID <> 2))
                                       BEGIN
                                          UPDATE CARD_ACCT SET STATUS = 2 WHERE CARD_ACCT_NO = @CardAccount
                                          SET @LockupCard = 1
                                       END
                                    
                                    -- Set ErrorID to Lockup amount exceeded.
                                    SET @ErrorID = 117
                                 END
                              
                              -- Validate the denomination.
                              -- Does the denomination played exist in the DENOM_TO_GAME table?
                              IF EXISTS (SELECT DENOM_VALUE
                                         FROM DENOM_TO_GAME_TYPE
                                            INNER JOIN BANK ON DENOM_TO_GAME_TYPE.GAME_TYPE_CODE = BANK.GAME_TYPE_CODE
                                            INNER JOIN MACH_SETUP ON BANK.BANK_NO = MACH_SETUP.BANK_NO
                                         WHERE MACH_NO = @MachineNumber AND DENOM_VALUE = @MachineDenom)
                                 BEGIN
                                    -- Yes, it exists, is the machine balance okay?
                                    IF (@Balance <> @MachineBal)
                                       -- No, the balance is off.
                                       BEGIN
                                          -- If in Cardless Play mode set error to 105, otherwise to 120.
                                          -- 120 locks machine, 105 does not.
                                          IF (@CardRequired = 0)
                                             SET @ErrorID = 105
                                          ELSE
                                             SET @ErrorID = 120
                                          -- In either case, error text is the same...
                                          SET @ErrorText = ', Machine balance should be: ' +
                                             CAST(@BaseBalance AS VarChar) +
                                             ', balance submitted was: ' + CAST(@MachineBal AS VarChar)
                                       END
                                 END
                              ELSE
                              -- Invalid Denomination.
                                 BEGIN
                                    SET @ErrorID = 107
                                    SET @ErrorText = ', Denomination submitted: ' + CAST(@MachineDenom AS VarChar) + ' is not valid.'
                                 END
                           END
                        ELSE
                           BEGIN
                              -- Coins Won <> Tier Coins Won
                              SET @ErrorID = 113
                              SET @SaveTrans = 1
                              SET @ErrorText = ', Tier submitted (' + CAST(@TierLevel AS VarChar) +
                                               ') is not valid. TierCoinsWon = ' + CAST(@TierCoinsWon AS VarChar) +
                                               ' MachineCoinsWon = ' + CAST(@CoinsWon AS VarChar)
                           END
                     END
                  ELSE
                     -- Deal is not active.
                     SET @ErrorID = 112
               END
            ELSE
               BEGIN
                  IF (@SequenceNum = @MachineSequence) AND (@LastBalance = @MachineBalance)
                     BEGIN
                        -- Send the Last Error
                        SET @ErrorID = @ErrorNum
                        SET @SaveTrans = 0
                     END
                  ELSE
                     BEGIN
                        -- Duplicate Ticket only if not bingo.
                        IF (@IsBingo = 0)
                           BEGIN
                              SET @ErrorID = 119
                           END
                        SET @SaveTrans = 1
                     END
               END
         END
      ELSE
         -- Deal does not exist.
         SET @ErrorID = 111
   END

-- If no other errors and ErrorOverride was set to allow update of game play, reset ErrorID now.
IF (@ErrorID = 0 AND @ErrorOverride <> 0)
   SET @ErrorID = @ErrorOverride

-- Handle any errors
IF (@ErrorID <> 0)
   BEGIN
      SELECT
         @ErrorDescription = ISNULL([DESCRIPTION], 'Undefined Error ' + CAST(@ErrorID AS VarChar(10))),
         @LockupMachine    = ISNULL(LOCKUP_MACHINE, 1),
         @ErrorTypeID      = ERROR_TYPE_ID
      FROM ERROR_LOOKUP
      WHERE ERROR_NO = @ErrorID
      
      -- If error 132 (promo balance mismatch that exceeds max bal adjustment value, force lockup.
      IF (@ErrorID = 132)
         SET @LockupMachine = 1
      
      -- If in Cardless Play mode, reset error text.
      IF (@CardRequired = 0)
         SET @ErrorDescription = dbo.CardlessErrorText(@ErrorDescription)
      
      -- Build Error Message
      SET @EventLogDesc = 'Description: ' + @ErrorDescription +
                          ', Card Account: ' + @CardAccount +
                          ', Machine Number: ' + @MachineNumber +
                          ', Casino Machine Number: ' + ISNULL(@CasinoMachNo, '<null>')
      
      IF (LEN(@ErrorText) > 0)
         SET @EventLogDesc = @EventLogDesc + @ErrorText
      
      -- Test if the Machine should be loocked up.
      IF (@LockupMachine <> 0)
         BEGIN
            UPDATE MACH_SETUP SET ACTIVE_FLAG = 0 WHERE MACH_NO = @MachineNumber AND ACTIVE_FLAG = 1
            
            SET @EventCode = 'SD'
         END
      
      -- Insert Error into the Casino_Event_Log
      INSERT INTO CASINO_EVENT_LOG
         (EVENT_CODE, EVENT_SOURCE, EVENT_DESC, ERROR_NO, MACH_NO)
      VALUES
         (@EventCode, @ErrorSource, @EventLogDesc, @ErrorID, @MachineNumber)
      
      -- Update Machine_Last_Play
      UPDATE MACH_LAST_PLAY SET ERROR_NO = @ErrorID WHERE MACH_NO = @MachineNumber
      
      -- If the error is a tab error and playing a paper game,
      -- record the the tab error in the TAB_ERROR table.
      IF (@ErrorTypeID = 1 AND @IsPaper = 1)
         BEGIN
            INSERT INTO TAB_ERROR
               (MACH_NO, ERROR_NO, EVENT_TIME, LOCATION_ID, TICKET_NO)
            VALUES
               (@MachineNumber, @ErrorID, @TimeStamp, @LocationID, @TicketNumber)
         END
   END

IF (@SaveTrans >= 2)
   BEGIN
      -- Increment Deal Statistics counters
      UPDATE DEAL_STATS SET
            PLAY_COUNT        = PLAY_COUNT        + 1,
            JACKPOT_COUNT     = JACKPOT_COUNT     + 1,
            AMOUNT_PLAYED     = AMOUNT_PLAYED     + @TabCost,
            TOTAL_WIN_AMOUNT  = TOTAL_WIN_AMOUNT  + @CTTransAmount,
            BASE_AMOUNT_WON   = BASE_AMOUNT_WON   + @BaseTrans,
            PROG_AMOUNT_WON   = PROG_AMOUNT_WON   + @ProgressiveAmt,
            PROG_CONTRIBUTION = PROG_CONTRIBUTION + @ProgContribution,
            LAST_PLAY         = @TimeStamp
      WHERE DEAL_NO = @DealNo
      
      -- If no rows were modified, the record doesn't exist - so create it.
      IF (@@ROWCOUNT = 0)
         BEGIN
            INSERT INTO DEAL_STATS
               (DEAL_NO, AMOUNT_PLAYED, JACKPOT_COUNT, PLAY_COUNT, BASE_AMOUNT_WON, TOTAL_WIN_AMOUNT,
                PROG_AMOUNT_WON, PROG_CONTRIBUTION, LAST_PLAY, FIRST_PLAY)
            VALUES
               (@DealNo, @TabCost, 1, 1, @BaseTrans, @CTTransAmount, @ProgressiveAmt, @ProgContribution, @TimeStamp, @TimeStamp)
         END
      
      DECLARE @MachineDenomCast smallmoney, @CoinsBetCast smallint, @LinesBetCast smallint
      SET @MachineDenomCast = CAST(@MachineDenom AS SmallMoney)
      SET @CoinsBetCast = CAST(@CoinsBet AS SmallInt)
      SET @LinesBetCast = CAST(@LinesBet AS SmallInt)
      
      EXEC tpUpdatePlayStatsHourlyAndDaily 
      @LocationIdPass = @LocationID,
@TimeStampPass = @TimeStamp,
@DenomPass = @MachineDenomCast,
@CoinsBetPass = @CoinsBetCast,
@LinesBetPass = @LinesBetCast,
@MachNoPass = @MachineNumber,
@CasinoMachNoPass = @CasinoMachNo,
@AcctDatePass = @AcctDate,
@DealNoPass = @DealNumber,
@GameCodePass = @MachGameCode,
@PlayCountPass = 1,
@JackpotCountPass = 1,
@AmountPlayedPass = @TabCost,
@AmountPlayedPromoPass = @PromoAmountPlayed,
@AmountJackpotPass = @CTTransAmount,
@AmountWonPromoPass = @PromoAmountWon,
@AmountProgPass = @ProgressiveAmt


      -- Update MACHINE_PLAY_STATS table...
      IF (@SummarizePlay = 1)
         EXEC tpUpdateMachinePlayStats
            @MachineNumber     = @MachineNumber,
            @CasinoMachineNbr  = @CasinoMachNo,
            @DealNo            = @DealNumber,
            @GameCode          = @MachGameCode,
            @Denom             = @MachineDenom,
            @CoinsBet          = @TotalCoinsBet,
            @LinesBet          = @LinesBet,
            @AmountPlayed      = @TabCost,
            @AmountWon         = @CTTransAmount,
            @AcctDate          = @AcctDate,
            @LocationID        = @LocationID
      
      -- Update MACHINE_METER table...
      UPDATE MACHINE_METER SET
         AMOUNT_PLAYED     = AMOUNT_PLAYED     + @TabCost,
         AMOUNT_WON        = AMOUNT_WON        + @CTTransAmount,
         PLAY_COUNT        = PLAY_COUNT        + 1,
         PROG_CONTRIBUTION = PROG_CONTRIBUTION + @ProgContribution
      WHERE
         MACH_NO = @MachineNumber
      
      -- If no row was modified, the record doesn't exist - so create it.
      IF (@@ROWCOUNT = 0)
         BEGIN
            INSERT INTO MACHINE_METER
               (MACH_NO, AMOUNT_PLAYED, AMOUNT_WON, PLAY_COUNT, PROG_CONTRIBUTION)
            VALUES
               (@MachineNumber, @TabCost, @CTTransAmount, 1, @ProgContribution)
         END
      
      -- Update MICS_STATS table if game does not support multiple bet levels per Deal...
      IF (@MultiBetDeals = 0)
         BEGIN
            UPDATE MICS_STATS SET
               WIN_COUNT   = WIN_COUNT   + 1,
               PROG_AMOUNT = PROG_AMOUNT + @ProgressiveAmt
            WHERE
               DEAL_NO    = @DealNumber AND
               WIN_AMOUNT = @BaseTrans
            
            -- If no MICS_STATS row modified, the record doesn't exist - so create it.
            IF (@@ROWCOUNT = 0)
               BEGIN
                  -- Perform the insertion.
                  INSERT INTO MICS_STATS
                     (DEAL_NO, WIN_AMOUNT, WIN_COUNT, PROG_AMOUNT)
                  VALUES
                     (@DealNumber, @BaseTrans, 1, @ProgressiveAmt)
               END
         END
   END

IF (@SaveTrans >= 1)
   -- Log transaction.
   BEGIN
      -- We will record the account balance + promo balance in the CASINO_TRANS.BALANCE column.
      SET @CTBalance = @Balance + @NewSystemPromoBal
      
      -- Perform the CASINO_TRANS insert.
      EXEC @CasinoTransID = tpInsertCasinoTrans
         @CasinoID, @DealNo, @RollNo, @TicketNo, @MachineDenom, @CTTransAmount,
         @Barcode, @TransID, @AcctDate, @TimeStamp, @MachineNumber,
         @CardAccount, @CTBalance, @MachGameCode, @CoinsBet, @LinesBet,
         @TierLevel, @PressUpCount, @LocationID, @MachineTimeStamp
   END

-- Did we get a balance error in Cardless Play mode?
IF (@ErrorID = 105)
   BEGIN
      -- Is the difference <= adjustment threshold?
      IF ((@MachineBal - @Balance) <= @MaxBalAdjust)
         BEGIN
            -- Yes, so we need to adjust the machine balance...
            EXEC tpAdjustMachineBalance
               @MachineNumber, @CardRequired, @MachineBal, @Balance, 'tpTransJ',
               @MachineTimeStamp, @CasinoID, @AcctDate, @MachGameCode, @LocationID
         END
      ELSE
         -- The difference exceeds the max adjustment value, force a lockup.
         BEGIN
            SET @LockupMachine = 1
            
            -- If debugging, save balance values...
            IF (@Debug = 1)
               BEGIN
                  SET @MsgText =
                     'tpTransJ Balance difference exceeds adjustment threshold: ' +
                     '  MachineBal: '   + ISNULL(CAST(@MachineBal AS VarChar), '<null>') +
                     '  SysBalance: '   + ISNULL(CAST(@Balance AS VarChar), '<null>') +
                     '  MaxBalAdjust: ' + ISNULL(CAST(@MaxBalAdjust AS VarChar), '<null>')
                  
                  EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
               END
         END
   END

IF (@SaveTrans >= 2)
   BEGIN
      -- Insert a row into the Jackpot table.
      INSERT INTO JACKPOT
         (TRANS_NO, DTIMESTAMP, CARD_ACCT_NO, MACH_NO, CASINO_MACH_NO, DEAL_NO,
          TICKET_NO, PLAY_COST, TRANS_ID, TRANS_AMT, PROG_AMT, LOCATION_ID)
      VALUES
         (@CasinoTransID, @TimeStamp, @CardAccount, @MachineNumber, @CasinoMachNo, @DealNo,
          @TicketNo, @TabCost, @TransID, @CTTransAmount, @ProgressiveAmt, @LocationID)
   END

-- Set sequence number in card account table to that of the CasinoTrans identity field.
IF (@LockupCard = 1 AND @CardRequired = 1)
   UPDATE CARD_ACCT SET SEQ_NUM = @CasinoTransID WHERE CARD_ACCT_NO = @CardAccount

-- If debugging, save return values...
IF (@Debug = 1)
   BEGIN
      SET @MsgText =
         'tpTransJ Return Values - ErrorID: ' + ISNULL(CAST(@ErrorID AS VarChar), '<null>') +
         '  ErrorDescription: ' + ISNULL(@ErrorDescription, '<null>') +
         '  LockupMachine: '    + ISNULL(CAST(@LockupMachine AS VarChar), '<null>') +
         '  ProgressiveAmt: '   + ISNULL(CAST(@ProgressiveAmt AS VarChar), '<null>') +
         '  Balance: '          + ISNULL(CAST(@Balance AS VarChar), '<null>')
      
      EXEC InsertDebugInfo @TransID, @MsgText, @MachNbrAsInt
   END

-- Return results to client
SELECT
   @ErrorID                        AS ErrorID,
   @ErrorDescription               AS ErrorDescription,
   @LockupMachine                  AS ShutDownFlag,
   CAST(@Balance * 100 AS Integer) AS Balance
GO
