SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/*
--------------------------------------------------------------------------------
User Defined Function IsValidVoucherCheckValue

Created 12-03-2010 by Terry Watkins

Purpose: Returns a boolean value indicating if a Voucher has a valid CHECK_VALUE.
         True means voucher has not been tampered with, False means either the
         Barcode, the Voucher Amount, or the REDEEMED_STATE was altered.

Returns: Bit value of 1 to indicate voucher is valid or 0 to indicate that the
         voucher has been tampered with.

   Note: Though similar to the Casino database version, this function takes
         a CheckValue argument generated by the client software.
         

Change Log

Changed By    Date           Database Version
  Change Description
--------------------------------------------------------------------------------
Terry Watkins 12-03-2010     v7.2.4
  Initial Coding
--------------------------------------------------------------------------------
*/
CREATE FUNCTION [dbo].[IsValidVoucherCheckValue] (@VoucherID INT, @CheckValue VARBINARY(8)) RETURNS Bit
AS
BEGIN
   -- [Variable Declarations]
   DECLARE @ReturnValue    Bit
   DECLARE @RowCount       Bit
   
   -- [Variable Initialization]
   SET @ReturnValue = 0
   
   -- Does the specified voucher exist?
   IF EXISTS(SELECT * FROM VOUCHER WHERE VOUCHER_ID = @VoucherID)
      -- Yes so retrieve some data...
      BEGIN
         -- Get a count of matching rows.
         SELECT @RowCount = COUNT(*) FROM VOUCHER
         WHERE VOUCHER_ID = @VoucherID AND CHECK_VALUE = @CheckValue
         
         -- If there is a match, we will have 1 row, if no match, then 0 rows.
         IF (@RowCount = 1) SET @ReturnValue = 1
      END
   
   -- Set the function return value.
   RETURN @ReturnValue
END
GO
