SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[sp_MSins_dboMACHINE_STATS_319_msrepl_ccs]
		@c1 int,
		@c2 char(5),
		@c3 varchar(8),
		@c4 datetime,
		@c5 int,
		@c6 varchar(3),
		@c7 int,
		@c8 int,
		@c9 int,
		@c10 int,
		@c11 smallint,
		@c12 smallint,
		@c13 int,
		@c14 int,
		@c15 money,
		@c16 money,
		@c17 money,
		@c18 money,
		@c19 money,
		@c20 money,
		@c21 money,
		@c22 money,
		@c23 money,
		@c24 money,
		@c25 int,
		@c26 int,
		@c27 int,
		@c28 int,
		@c29 int,
		@c30 int,
		@c31 int,
		@c32 int,
		@c33 money,
		@c34 int,
		@c35 money,
		@c36 int,
		@c37 money,
		@c38 int,
		@c39 money,
		@c40 int,
		@c41 money,
		@c42 int,
		@c43 smallint,
		@c44 smallint,
		@c45 smallint,
		@c46 smallint,
		@c47 money,
		@c48 money
as
begin
if exists (select * 
             from [dbo].[MACHINE_STATS]
            where [MACHINE_STATS_ID] = @c1
              and [LOCATION_ID] = @c7)
begin
update [dbo].[MACHINE_STATS] set
		[MACH_NO] = @c2,
		[CASINO_MACH_NO] = @c3,
		[ACCT_DATE] = @c4,
		[DEAL_NO] = @c5,
		[GAME_CODE] = @c6,
		[PLAY_COUNT] = @c8,
		[LOSS_COUNT] = @c9,
		[WIN_COUNT] = @c10,
		[JACKPOT_COUNT] = @c11,
		[FORFEIT_COUNT] = @c12,
		[TICKET_IN_COUNT] = @c13,
		[TICKET_OUT_COUNT] = @c14,
		[AMOUNT_IN] = @c15,
		[AMOUNT_PLAYED] = @c16,
		[AMOUNT_LOST] = @c17,
		[AMOUNT_WON] = @c18,
		[AMOUNT_JACKPOT] = @c19,
		[AMOUNT_FORFEITED] = @c20,
		[AMOUNT_PROG] = @c21,
		[TICKET_IN_AMOUNT] = @c22,
		[TICKET_OUT_AMOUNT] = @c23,
		[PROG_CONTRIBUTION] = @c24,
		[BILL_COUNT_1] = @c25,
		[BILL_COUNT_2] = @c26,
		[BILL_COUNT_5] = @c27,
		[BILL_COUNT_10] = @c28,
		[BILL_COUNT_20] = @c29,
		[BILL_COUNT_50] = @c30,
		[BILL_COUNT_100] = @c31,
		[BILL_COUNT_OTHER] = @c32,
		[PROMO_IN_AMOUNT] = @c33,
		[PROMO_IN_COUNT] = @c34,
		[EFT_IN_AMOUNT] = @c35,
		[EFT_IN_COUNT] = @c36,
		[EFT_OUT_AMOUNT] = @c37,
		[EFT_OUT_COUNT] = @c38,
		[EFT_PROMO_IN_AMOUNT] = @c39,
		[EFT_PROMO_IN_COUNT] = @c40,
		[EFT_PROMO_OUT_AMOUNT] = @c41,
		[EFT_PROMO_OUT_COUNT] = @c42,
		[MAIN_DOOR_OPEN_COUNT] = @c43,
		[CASH_DOOR_OPEN_COUNT] = @c44,
		[LOGIC_DOOR_OPEN_COUNT] = @c45,
		[BASE_DOOR_OPEN_COUNT] = @c46,
		[AMOUNT_PLAYED_PROMO] = @c47,
		[AMOUNT_WON_PROMO] = @c48
where [MACHINE_STATS_ID] = @c1
  and [LOCATION_ID] = @c7
end
else
begin
	insert into [dbo].[MACHINE_STATS](
		[MACHINE_STATS_ID],
		[MACH_NO],
		[CASINO_MACH_NO],
		[ACCT_DATE],
		[DEAL_NO],
		[GAME_CODE],
		[LOCATION_ID],
		[PLAY_COUNT],
		[LOSS_COUNT],
		[WIN_COUNT],
		[JACKPOT_COUNT],
		[FORFEIT_COUNT],
		[TICKET_IN_COUNT],
		[TICKET_OUT_COUNT],
		[AMOUNT_IN],
		[AMOUNT_PLAYED],
		[AMOUNT_LOST],
		[AMOUNT_WON],
		[AMOUNT_JACKPOT],
		[AMOUNT_FORFEITED],
		[AMOUNT_PROG],
		[TICKET_IN_AMOUNT],
		[TICKET_OUT_AMOUNT],
		[PROG_CONTRIBUTION],
		[BILL_COUNT_1],
		[BILL_COUNT_2],
		[BILL_COUNT_5],
		[BILL_COUNT_10],
		[BILL_COUNT_20],
		[BILL_COUNT_50],
		[BILL_COUNT_100],
		[BILL_COUNT_OTHER],
		[PROMO_IN_AMOUNT],
		[PROMO_IN_COUNT],
		[EFT_IN_AMOUNT],
		[EFT_IN_COUNT],
		[EFT_OUT_AMOUNT],
		[EFT_OUT_COUNT],
		[EFT_PROMO_IN_AMOUNT],
		[EFT_PROMO_IN_COUNT],
		[EFT_PROMO_OUT_AMOUNT],
		[EFT_PROMO_OUT_COUNT],
		[MAIN_DOOR_OPEN_COUNT],
		[CASH_DOOR_OPEN_COUNT],
		[LOGIC_DOOR_OPEN_COUNT],
		[BASE_DOOR_OPEN_COUNT],
		[AMOUNT_PLAYED_PROMO],
		[AMOUNT_WON_PROMO]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23,
    @c24,
    @c25,
    @c26,
    @c27,
    @c28,
    @c29,
    @c30,
    @c31,
    @c32,
    @c33,
    @c34,
    @c35,
    @c36,
    @c37,
    @c38,
    @c39,
    @c40,
    @c41,
    @c42,
    @c43,
    @c44,
    @c45,
    @c46,
    @c47,
    @c48	) 
end
end
GO
