SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[sp_MSins_dboCASINO_319_msrepl_ccs]
		@c1 char(6),
		@c2 varchar(48),
		@c3 varchar(64),
		@c4 varchar(64),
		@c5 varchar(48),
		@c6 varchar(32),
		@c7 char(2),
		@c8 varchar(12),
		@c9 varchar(20),
		@c10 varchar(20),
		@c11 bit,
		@c12 smallmoney,
		@c13 datetime,
		@c14 datetime,
		@c15 smallint,
		@c16 smallint,
		@c17 tinyint,
		@c18 bit,
		@c19 bit,
		@c20 bit,
		@c21 bit,
		@c22 char(1),
		@c23 int,
		@c24 int,
		@c25 bit,
		@c26 bit,
		@c27 bit,
		@c28 smallmoney,
		@c29 bit,
		@c30 int,
		@c31 decimal(4,2),
		@c32 bit,
		@c33 bit,
		@c34 bit,
		@c35 bit,
		@c36 bit,
		@c37 bit,
		@c38 bit,
		@c39 smallint,
		@c40 money,
		@c41 int,
		@c42 int,
		@c43 money,
		@c44 decimal(4,2),
		@c45 varchar(32),
		@c46 varchar(6)
as
begin
if exists (select * 
             from [dbo].[CASINO]
            where [CAS_ID] = @c1)
begin
update [dbo].[CASINO] set
		[CAS_NAME] = @c2,
		[ADDRESS1] = @c3,
		[ADDRESS2] = @c4,
		[CONTACT_NAME] = @c5,
		[CITY] = @c6,
		[STATE] = @c7,
		[ZIP] = @c8,
		[PHONE] = @c9,
		[FAX] = @c10,
		[SETASDEFAULT] = @c11,
		[LOCKUP_AMT] = @c12,
		[FROM_TIME] = @c13,
		[TO_TIME] = @c14,
		[CLAIM_TIMEOUT] = @c15,
		[DAUB_TIMEOUT] = @c16,
		[CARD_TYPE] = @c17,
		[PLAYER_CARD] = @c18,
		[REPRINT_TICKET] = @c19,
		[RECEIPT_PRINTER] = @c20,
		[DISPLAY_PROGRESSIVE] = @c21,
		[PT_AWARD_TYPE] = @c22,
		[TPI_ID] = @c23,
		[TPI_PROPERTY_ID] = @c24,
		[PROMOTIONAL_PLAY] = @c25,
		[PIN_REQUIRED] = @c26,
		[RS_AND_PPP] = @c27,
		[PPP_AMOUNT] = @c28,
		[JACKPOT_LOCKUP] = @c29,
		[CASHOUT_TIMEOUT] = @c30,
		[AMUSEMENT_TAX_PCT] = @c31,
		[AUTO_DROP] = @c32,
		[SUMMARIZE_PLAY] = @c33,
		[PRINT_PROMO_TICKETS] = @c34,
		[BINGO_FREE_SQUARE] = @c35,
		[PRINT_REDEMPTION_TICKETS] = @c36,
		[PRINT_RAFFLE_TICKETS] = @c37,
		[AUTHENTICATE_APPS] = @c38,
		[PROG_REQUEST_SECONDS] = @c39,
		[MAX_BAL_ADJUSTMENT] = @c40,
		[MIN_DI_VERSION] = @c41,
		[LOCATION_ID] = @c42,
		[PAYOUT_THRESHOLD] = @c43,
		[RETAIL_REV_SHARE] = @c44,
		[SWEEP_ACCT] = @c45,
		[RETAILER_NUMBER] = @c46
where [CAS_ID] = @c1
end
else
begin
	insert into [dbo].[CASINO](
		[CAS_ID],
		[CAS_NAME],
		[ADDRESS1],
		[ADDRESS2],
		[CONTACT_NAME],
		[CITY],
		[STATE],
		[ZIP],
		[PHONE],
		[FAX],
		[SETASDEFAULT],
		[LOCKUP_AMT],
		[FROM_TIME],
		[TO_TIME],
		[CLAIM_TIMEOUT],
		[DAUB_TIMEOUT],
		[CARD_TYPE],
		[PLAYER_CARD],
		[REPRINT_TICKET],
		[RECEIPT_PRINTER],
		[DISPLAY_PROGRESSIVE],
		[PT_AWARD_TYPE],
		[TPI_ID],
		[TPI_PROPERTY_ID],
		[PROMOTIONAL_PLAY],
		[PIN_REQUIRED],
		[RS_AND_PPP],
		[PPP_AMOUNT],
		[JACKPOT_LOCKUP],
		[CASHOUT_TIMEOUT],
		[AMUSEMENT_TAX_PCT],
		[AUTO_DROP],
		[SUMMARIZE_PLAY],
		[PRINT_PROMO_TICKETS],
		[BINGO_FREE_SQUARE],
		[PRINT_REDEMPTION_TICKETS],
		[PRINT_RAFFLE_TICKETS],
		[AUTHENTICATE_APPS],
		[PROG_REQUEST_SECONDS],
		[MAX_BAL_ADJUSTMENT],
		[MIN_DI_VERSION],
		[LOCATION_ID],
		[PAYOUT_THRESHOLD],
		[RETAIL_REV_SHARE],
		[SWEEP_ACCT],
		[RETAILER_NUMBER]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23,
    @c24,
    @c25,
    @c26,
    @c27,
    @c28,
    @c29,
    @c30,
    @c31,
    @c32,
    @c33,
    @c34,
    @c35,
    @c36,
    @c37,
    @c38,
    @c39,
    @c40,
    @c41,
    @c42,
    @c43,
    @c44,
    @c45,
    @c46	) 
end
end
GO
