SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[sp_MSins_dboMACH_SETUP_319_msrepl_ccs]
		@c1 char(5),
		@c2 int,
		@c3 varchar(64),
		@c4 char(1),
		@c5 varchar(3),
		@c6 int,
		@c7 varchar(8),
		@c8 varchar(24),
		@c9 bit,
		@c10 datetime,
		@c11 tinyint,
		@c12 bit,
		@c13 money,
		@c14 money,
		@c15 datetime,
		@c16 datetime,
		@c17 datetime,
		@c18 varchar(15),
		@c19 bit,
		@c20 int,
		@c21 bit,
		@c22 varchar(16),
		@c23 varchar(16),
		@c24 varchar(16),
		@c25 varchar(16),
		@c26 varchar(16),
		@c27 varchar(16),
		@c28 varchar(16),
		@c29 varchar(16),
		@c30 varchar(16),
		@c31 datetime,
		@c32 datetime
as
begin
if exists (select * 
             from [dbo].[MACH_SETUP]
            where [MACH_NO] = @c1
              and [LOCATION_ID] = @c2)
begin
update [dbo].[MACH_SETUP] set
		[MODEL_DESC] = @c3,
		[TYPE_ID] = @c4,
		[GAME_CODE] = @c5,
		[BANK_NO] = @c6,
		[CASINO_MACH_NO] = @c7,
		[IP_ADDRESS] = @c8,
		[PLAY_STATUS] = @c9,
		[PLAY_STATUS_CHANGED] = @c10,
		[ACTIVE_FLAG] = @c11,
		[REMOVED_FLAG] = @c12,
		[BALANCE] = @c13,
		[PROMO_BALANCE] = @c14,
		[LAST_ACTIVITY] = @c15,
		[LAST_CONNECT] = @c16,
		[LAST_DISCONNECT] = @c17,
		[MACH_SERIAL_NO] = @c18,
		[VOUCHER_PRINTING] = @c19,
		[METER_TRANS_NO] = @c20,
		[SD_RS_FLAG] = @c21,
		[GAME_RELEASE] = @c22,
		[GAME_CORE_LIB_VERSION] = @c23,
		[GAME_LIB_VERSION] = @c24,
		[MATH_DLL_VERSION] = @c25,
		[MATH_LIB_VERSION] = @c26,
		[OS_VERSION] = @c27,
		[SYSTEM_VERSION] = @c28,
		[SYSTEM_LIB_A_VERSION] = @c29,
		[SYSTEM_CORE_LIB_VERSION] = @c30,
		[InstallDate] = @c31,
		[RemoveDate] = @c32
where [MACH_NO] = @c1
  and [LOCATION_ID] = @c2
end
else
begin
	insert into [dbo].[MACH_SETUP](
		[MACH_NO],
		[LOCATION_ID],
		[MODEL_DESC],
		[TYPE_ID],
		[GAME_CODE],
		[BANK_NO],
		[CASINO_MACH_NO],
		[IP_ADDRESS],
		[PLAY_STATUS],
		[PLAY_STATUS_CHANGED],
		[ACTIVE_FLAG],
		[REMOVED_FLAG],
		[BALANCE],
		[PROMO_BALANCE],
		[LAST_ACTIVITY],
		[LAST_CONNECT],
		[LAST_DISCONNECT],
		[MACH_SERIAL_NO],
		[VOUCHER_PRINTING],
		[METER_TRANS_NO],
		[SD_RS_FLAG],
		[GAME_RELEASE],
		[GAME_CORE_LIB_VERSION],
		[GAME_LIB_VERSION],
		[MATH_DLL_VERSION],
		[MATH_LIB_VERSION],
		[OS_VERSION],
		[SYSTEM_VERSION],
		[SYSTEM_LIB_A_VERSION],
		[SYSTEM_CORE_LIB_VERSION],
		[InstallDate],
		[RemoveDate]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23,
    @c24,
    @c25,
    @c26,
    @c27,
    @c28,
    @c29,
    @c30,
    @c31,
    @c32	) 
end
end
GO
