'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("eDeal")>  _
        Public Property EdealDBCatalog() As String
            Get
                Return CType(Me("EdealDBCatalog"),String)
            End Get
            Set
                Me("EdealDBCatalog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mas")>  _
        Public Property DatabaseUserID() As String
            Get
                Return CType(Me("DatabaseUserID"),String)
            End Get
            Set
                Me("DatabaseUserID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("J~6Gl#hJ")>  _
        Public Property DatabasePassword() As String
            Get
                Return CType(Me("DatabasePassword"),String)
            End Get
            Set
                Me("DatabasePassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\Data\")>  _
        Public Property DataFolder() As String
            Get
                Return CType(Me("DataFolder"),String)
            End Get
            Set
                Me("DataFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{0}_ExportData.xml")>  _
        Public Property DataSourceFile() As String
            Get
                Return CType(Me("DataSourceFile"),String)
            End Get
            Set
                Me("DataSourceFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FreeSpaceCheck() As Boolean
            Get
                Return CType(Me("FreeSpaceCheck"),Boolean)
            End Get
            Set
                Me("FreeSpaceCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LRDealImport.exe,DgeSqlDataAccess.dll,DgeHashLib.dll")>  _
        Public Property AppAuthList() As String
            Get
                Return CType(Me("AppAuthList"),String)
            End Get
            Set
                Me("AppAuthList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60, 60")>  _
        Public Property MDIStartLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("MDIStartLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MDIStartLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1200, 800")>  _
        Public Property MDIStartSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("MDIStartSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("MDIStartSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Normal")>  _
        Public Property MDIStartFWS() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("MDIStartFWS"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("MDIStartFWS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5006006004")>  _
        Public Property MinDealGenVersion() As Long
            Get
                Return CType(Me("MinDealGenVersion"),Long)
            End Get
            Set
                Me("MinDealGenVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60, 60")>  _
        Public Property AddBankLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("AddBankLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("AddBankLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("594, 370")>  _
        Public Property AddBankSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("AddBankSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("AddBankSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("160, 60")>  _
        Public Property AboutFormLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("AboutFormLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("AboutFormLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("540, 400")>  _
        Public Property AboutFormSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("AboutFormSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("AboutFormSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LotteryRetail")>  _
        Public Property LotteryRetailDBCatalog() As String
            Get
                Return CType(Me("LotteryRetailDBCatalog"),String)
            End Get
            Set
                Me("LotteryRetailDBCatalog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("(local)")>  _
        Public Property DatabaseServer() As String
            Get
                Return CType(Me("DatabaseServer"),String)
            End Get
            Set
                Me("DatabaseServer") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LRDealImport.My.MySettings
            Get
                Return Global.LRDealImport.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
