USE [Master]

IF SUSER_ID('mas') IS NULL
CREATE LOGIN [mas] WITH PASSWORD = 'spoam6us',
CHECK_POLICY = OFF

IF SUSER_ID('sqljobs') IS NULL
CREATE LOGIN [sqljobs] WITH PASSWORD = 'sq1acc3ss',
CHECK_POLICY = OFF

IF SUSER_ID('reports') IS NULL
CREATE LOGIN [reports] WITH PASSWORD = 'r3port$',
CHECK_POLICY = OFF

IF SUSER_ID('tp') IS NULL
CREATE LOGIN [tp] WITH PASSWORD = 'tp4ssw0rd',
CHECK_POLICY = OFF
