'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("J~6Gl#hJ")>  _
        Public ReadOnly Property DBKey() As String
            Get
                Return CType(Me("DBKey"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EPSON TM-T88V ReceiptE4")>  _
        Public Property ReceiptPrinter() As String
            Get
                Return CType(Me("ReceiptPrinter"),String)
            End Get
            Set
                Me("ReceiptPrinter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft XPS Document Writer")>  _
        Public Property ReportPrinter() As String
            Get
                Return CType(Me("ReportPrinter"),String)
            End Get
            Set
                Me("ReportPrinter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(" ; ; ; ; ")>  _
        Public Property LastReceipt() As String
            Get
                Return CType(Me("LastReceipt"),String)
            End Get
            Set
                Me("LastReceipt") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LotteryManagementSystem.exe,DgeSqlDataAccess.dll,DgeHashLib.dll")>  _
        Public ReadOnly Property AppAuthList() As String
            Get
                Return CType(Me("AppAuthList"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportViewSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("ReportViewSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("ReportViewSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property ReportViewLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("ReportViewLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("ReportViewLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600, 300")>  _
        Public Property AppUserSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("AppUserSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("AppUserSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property AppUserLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("AppUserLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("AppUserLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("430, 400")>  _
        Public Property FlexNumberSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("FlexNumberSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("FlexNumberSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property FlexNumberLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("FlexNumberLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("FlexNumberLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("700, 300")>  _
        Public Property LocationViewSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("LocationViewSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("LocationViewSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property LocationViewLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("LocationViewLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("LocationViewLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastLoginID() As String
            Get
                Return CType(Me("LastLoginID"),String)
            End Get
            Set
                Me("LastLoginID") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=dccentraltest;Initial Catalog=LotteryCentral;User Id=mas;Password={0}"& _ 
            ";")>  _
        Public ReadOnly Property DBConnect() As String
            Get
                Return CType(Me("DBConnect"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://local:80/ReportServer/ReportService2010.asmx")>  _
        Public ReadOnly Property LotteryManagementSystem_SqlReportingWebService2010_ReportingService2010() As String
            Get
                Return CType(Me("LotteryManagementSystem_SqlReportingWebService2010_ReportingService2010"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LotteryManagementSystem.My.MySettings
            Get
                Return Global.LotteryManagementSystem.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
